'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { getSupabaseBrowser } from '../lib/supabase-browser';

const label={pending:'Menunggu',valid:'Valid',verified:'Terverifikasi',rejected:'Ditolak',incomplete:'Belum lengkap'};
const roleLabel={super_admin:'Super Admin',event_admin:'Admin Event',document_verifier:'Verifikator Dokumen',payment_verifier:'Verifikator Pembayaran',viewer:'Viewer'};
const docLabel={stra:'STRA',experience:'Bukti pengalaman',payment_proof:'Bukti pembayaran'};
function badge(value){const cls=['verified','valid'].includes(value)?'status-ok':value==='rejected'?'status-bad':'status-pending';return <span className={`status ${cls}`}>{label[value]||value}</span>}
function formatDate(value){if(!value)return '—';try{return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(value))}catch{return value}}
function dateTimeLocal(value){if(!value)return '';try{const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value));const get=t=>parts.find(x=>x.type===t)?.value||'';return `${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`}catch{return String(value).slice(0,16)}}
function docStatusClass(status){return status==='valid'?'reviewed':status==='rejected'?'rejected':'pending'}
function displayParticipantEmail(r){return r?.email_needs_update?(r.legacy_contact_email||r.email):r?.email}

export default function AdminDashboard(){
  const [rows,setRows]=useState([]),[settings,setSettings]=useState(null),[adminUser,setAdminUser]=useState(null),[team,setTeam]=useState([]),[announcements,setAnnouncements]=useState([]),[accessSettings,setAccessSettings]=useState(null);
  const [announcementSubject,setAnnouncementSubject]=useState(''),[announcementAudience,setAnnouncementAudience]=useState('all'),[announcementBusy,setAnnouncementBusy]=useState(false);
  const editorRef=useRef(null);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[view,setView]=useState('overview');
  const [q,setQ]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[modeFilter,setModeFilter]=useState('all');
  const [docModal,setDocModal]=useState(null),[confirm,setConfirm]=useState(null),[reviewBusy,setReviewBusy]=useState(false);
  const [rejectReason,setRejectReason]=useState(''),[nextAction,setNextAction]=useState('');

  async function token(){const {data}=await getSupabaseBrowser().auth.getSession();return data.session?.access_token||''}
  async function api(url,opts={}){const t=await token();if(!t){location.href='/admin/login';throw new Error('Sesi berakhir.')}const r=await fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>({}));if(r.status===403){location.href='/admin/login';throw new Error('Akses panitia ditolak.')}if(!r.ok)throw new Error(j.message||'Request gagal');return j}
  async function load(){try{setError('');const [a,b,c,d]=await Promise.all([api('/api/admin/registrations'),api('/api/admin/settings'),api('/api/admin/announcements'),api('/api/admin/event-access')]);setRows(a.registrations||[]);setAdminUser(a.adminUser||null);setSettings(b.event);setAnnouncements(c.announcements||[]);setAccessSettings(d);if(a.adminUser?.role==='super_admin'){const teamData=await api('/api/admin/users');setTeam(teamData.users||[])}}catch(e){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);

  async function saveSettings(e){e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));try{setError('');await api('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setNotice('Pengaturan form berhasil disimpan.');await load()}catch(err){setError(err.message)}}
  async function saveEventAccess(e){e.preventDefault();const fd=new FormData(e.currentTarget);const body={offline_qr_enabled:fd.get('offline_qr_enabled')==='on',offline_qr_release_at:fd.get('offline_qr_release_at')||'',online_access_enabled:fd.get('online_access_enabled')==='on',online_access_release_at:fd.get('online_access_release_at')||'',zoom_url:fd.get('zoom_url')||''};try{setError('');await api('/api/admin/event-access',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice('Pengaturan akses acara berhasil disimpan.');await load()}catch(err){setError(err.message)}}
  async function openDoc(row,type){try{setError('');setDocModal({loading:true,row,type});const t=await token();const r=await fetch(`/api/documents/${row.id}?type=${type}`,{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(!r.ok)throw new Error(j.message||'Dokumen tidak tersedia');setDocModal({loading:false,row,type,...j})}catch(e){setDocModal(null);setError(e.message)}}
  function askVerify(){if(!docModal?.document)return;setConfirm({mode:'verify',previousStatus:docModal.document.status})}
  function askReject(){if(!docModal?.document)return;setRejectReason(docModal.document.review_note||'');setNextAction(docModal.type==='payment_proof'?'Silakan unggah ulang bukti pembayaran yang benar melalui Dashboard Peserta.':'Silakan unggah ulang dokumen yang benar dan dapat dibaca melalui Dashboard Peserta.');setConfirm({mode:'reject',previousStatus:docModal.document.status})}
  async function submitReview(status){if(!docModal)return;try{setReviewBusy(true);setError('');const body={registrationId:docModal.row.id,documentType:docModal.type,status};if(status==='rejected'){body.reason=rejectReason;body.nextAction=nextAction;if(!rejectReason.trim()||!nextAction.trim())throw new Error('Alasan penolakan dan langkah selanjutnya wajib diisi.')}const j=await api('/api/admin/documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice(status==='valid'?'Dokumen berhasil diverifikasi.':`Dokumen ditolak. ${j.emailSent?'Email instruksi sudah dikirim ke peserta.':'Status tersimpan; periksa log email jika pesan belum terkirim.'}`);setConfirm(null);setDocModal(null);await load()}catch(e){setError(e.message)}finally{setReviewBusy(false)}}
  async function addAdmin(e){e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));try{setError('');const j=await api('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice(j.warning||j.message||'Panitia berhasil ditambahkan.');form.reset();const c=await api('/api/admin/users');setTeam(c.users||[])}catch(err){setError(err.message)}}
  async function toggleAdmin(user){try{await api('/api/admin/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:user.email,active:!user.active})});const c=await api('/api/admin/users');setTeam(c.users||[])}catch(e){setError(e.message)}}
  async function openBilling(row,kind){try{setError('');const t=await token();const r=await fetch(`/api/billing/${kind}?id=${row.id}`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.message||'Dokumen belum tersedia.')}const blob=await r.blob();const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setError(e.message)}}
  async function exportXlsx(){try{setError('');const t=await token();const r=await fetch('/api/admin/export',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({ids:filtered.map(x=>x.id)})});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.message||'Export gagal.')}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='pendaftar-preseptor-2026.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){setError(e.message)}}
  function printRows(){
    if(!filtered.length)return;
    const tr=filtered.map((r,i)=>`<tr><td>${i+1}</td><td>${escapePrint(r.registration_code)}</td><td>${escapePrint(r.full_name)}</td><td>${escapePrint(displayParticipantEmail(r))}</td><td>${escapePrint(r.whatsapp)}</td><td>${escapePrint(r.university)}</td><td>${escapePrint(r.attendance_mode)}</td><td>${escapePrint(label[r.requirements_status]||r.requirements_status)}</td><td>${escapePrint(label[r.payment_status]||r.payment_status)}</td></tr>`).join('');
    const printedAt=new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date());
    const html=`<!doctype html><html><head><meta charset="utf-8"><title>Data Pendaftar Preseptor</title><style>@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#14204f;margin:0}.letterhead{width:100%;max-height:88px;object-fit:contain;object-position:left center;margin-bottom:10px}.head{border-top:2px solid #173f9d;padding-top:9px;margin-bottom:14px}.head h1{font-size:18px;margin:0 0 4px;color:#11185d}.head p{font-size:10px;color:#657395;margin:0}.summary{display:flex;gap:8px;margin:0 0 12px;font-size:10px}.summary span{border:1px solid #d7e1f0;border-radius:999px;padding:5px 9px;background:#f7faff}table{border-collapse:collapse;width:100%;font-size:8px;table-layout:fixed}th,td{border:1px solid #cbd7e9;padding:5px;text-align:left;vertical-align:top;word-break:break-word}th{background:#11185d;color:#fff;font-size:7.5px;text-transform:uppercase;letter-spacing:.02em}tbody tr:nth-child(even){background:#f8faff}.c-no{width:28px}.c-reg{width:112px}.c-name{width:125px}.c-email{width:145px}.c-wa{width:92px}.c-home{width:145px}.c-mode{width:54px}.c-status{width:80px}.foot{margin-top:9px;font-size:8px;color:#7b879e}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body><img class="letterhead" src="${location.origin}/aptfi-letterhead.png" alt="APTFI"><div class="head"><h1>Data Pendaftar Pelatihan Preseptor APTFI 2026</h1><p>Daftar sesuai filter aktif pada Dashboard Panitia</p></div><div class="summary"><span><strong>${filtered.length}</strong> data</span><span>Dicetak ${escapePrint(printedAt)} WIB</span></div><table><thead><tr><th class="c-no">No</th><th class="c-reg">No. Pendaftaran</th><th class="c-name">Nama</th><th class="c-email">Email</th><th class="c-wa">WhatsApp</th><th class="c-home">Homebase</th><th class="c-mode">Mode</th><th class="c-status">Persyaratan</th><th class="c-status">Pembayaran</th></tr></thead><tbody>${tr}</tbody></table><div class="foot">APTFI · Pelatihan Preseptor 2026</div></body></html>`;
    const iframe=document.createElement('iframe');
    iframe.setAttribute('aria-hidden','true');
    iframe.style.position='fixed';
    iframe.style.right='0';
    iframe.style.bottom='0';
    iframe.style.width='1px';
    iframe.style.height='1px';
    iframe.style.opacity='0';
    iframe.style.pointerEvents='none';
    iframe.style.border='0';
    document.body.appendChild(iframe);
    let printStarted=false;
    const cleanup=()=>{setTimeout(()=>iframe.remove(),700)};
    const runPrint=()=>{if(printStarted)return;printStarted=true;try{iframe.contentWindow?.focus();iframe.contentWindow?.print()}finally{cleanup()}};
    const doc=iframe.contentDocument||iframe.contentWindow?.document;
    if(!doc){iframe.remove();setError('Browser tidak dapat menyiapkan halaman print.');return}
    doc.open();doc.write(html);doc.close();
    const logo=doc.querySelector('.letterhead');
    if(logo&&!logo.complete){logo.addEventListener('load',()=>setTimeout(runPrint,120),{once:true});logo.addEventListener('error',()=>setTimeout(runPrint,120),{once:true});setTimeout(runPrint,900)}else{setTimeout(runPrint,180)}
  }
  function editorCommand(command,value=null){editorRef.current?.focus();document.execCommand(command,false,value)}
  async function publishAnnouncement(e){e.preventDefault();const bodyHtml=editorRef.current?.innerHTML||'';try{setAnnouncementBusy(true);setError('');const j=await api('/api/admin/announcements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject:announcementSubject,audience:announcementAudience,bodyHtml})});setNotice(`Pengumuman dipublikasikan ke ${j.recipientCount} peserta.${j.emailSent?' Email berhasil dikirim.':j.emailError?' Email mengalami kendala: '+j.emailError:''}`);setAnnouncementSubject('');setAnnouncementAudience('all');if(editorRef.current)editorRef.current.innerHTML='';const c=await api('/api/admin/announcements');setAnnouncements(c.announcements||[])}catch(e){setError(e.message)}finally{setAnnouncementBusy(false)}}
  async function logout(){await getSupabaseBrowser().auth.signOut();location.href='/admin/login'}

  const filtered=useMemo(()=>rows.filter(r=>{const hay=`${r.full_name} ${displayParticipantEmail(r)} ${r.registration_code} ${r.university||''} ${r.stra_number||''}`.toLowerCase();if(q&&!hay.includes(q.toLowerCase()))return false;if(modeFilter!=='all'&&r.attendance_mode!==modeFilter)return false;if(statusFilter==='docs_pending'&&r.requirements_status!=='pending'&&r.requirements_status!=='incomplete')return false;if(statusFilter==='pay_pending'&&r.payment_status!=='pending')return false;if(statusFilter==='verified'&&r.overall_status!=='verified')return false;if(statusFilter==='rejected'&&r.requirements_status!=='rejected'&&r.payment_status!=='rejected')return false;return true}),[rows,q,statusFilter,modeFilter]);
  const total=rows.length,req=rows.filter(x=>['pending','incomplete'].includes(x.requirements_status)).length,pay=rows.filter(x=>x.payment_status==='pending').length,verified=rows.filter(x=>x.overall_status==='verified').length;
  const offlineVerified=rows.filter(x=>x.attendance_mode==='Offline'&&x.overall_status==='verified').length,checkedIn=rows.filter(x=>x.attendance_mode==='Offline'&&x.checked_in_at).length,onlineVerified=rows.filter(x=>x.attendance_mode==='Online'&&x.overall_status==='verified').length;

  if(loading)return <div className="admin-loading"><div className="spinner"/><p>Memuat dashboard panitia...</p></div>;

  return <div className="admin-app">
    <aside className="admin-sidebar">
      <div className="admin-logo"><img src="/aptfi-logo.png" alt="APTFI"/><small>Preseptor 2026</small></div>
      <nav className="admin-nav">
        <button className={view==='overview'?'active':''} onClick={()=>setView('overview')}><span>⌂</span>Ringkasan</button>
        <button className={view==='participants'?'active':''} onClick={()=>setView('participants')}><span>▦</span>Pendaftar <em>{total}</em></button>
        <button className={view==='settings'?'active':''} onClick={()=>setView('settings')}><span>⚙</span>Status Form</button>
        <button className={view==='announcements'?'active':''} onClick={()=>setView('announcements')}><span>✉</span>Pengumuman</button>
        <button className={view==='access'?'active':''} onClick={()=>setView('access')}><span>▣</span>Akses Acara</button>
        <button onClick={()=>location.href='/admin/checkin'}><span>⌁</span>Check-in</button>
        {adminUser?.role==='super_admin'&&<button className={view==='team'?'active':''} onClick={()=>setView('team')}><span>♙</span>Tim Panitia</button>}
      </nav>
      <div className="admin-profile"><div className="avatar">{(adminUser?.display_name||adminUser?.email||'A').slice(0,1).toUpperCase()}</div><div><strong>{adminUser?.display_name||'Panitia APTFI'}</strong><small>{roleLabel[adminUser?.role]||adminUser?.role}</small></div><button onClick={logout} title="Keluar">↗</button></div>
    </aside>

    <main className="admin-main">
      <header className="admin-header"><div><div className="eyebrow brand-blue">Dashboard Panitia</div><h1>{view==='overview'?'Ringkasan Kegiatan':view==='participants'?'Daftar Pendaftar':view==='settings'?'Pengaturan Pendaftaran':view==='announcements'?'Pengumuman':view==='access'?'Akses Pelaksanaan':'Tim Panitia'}</h1></div><div className="admin-header-actions"><a className="btn btn-secondary" href="/" target="_blank">Lihat Situs ↗</a></div></header>
      <div className="admin-mobile-nav"><button onClick={()=>setView('overview')}>Ringkasan</button><button onClick={()=>setView('participants')}>Pendaftar</button><button onClick={()=>setView('settings')}>Form</button><button onClick={()=>setView('announcements')}>Pengumuman</button><button onClick={()=>setView('access')}>Akses</button><button onClick={()=>location.href='/admin/checkin'}>Check-in</button>{adminUser?.role==='super_admin'&&<button onClick={()=>setView('team')}>Tim</button>}</div>
      {error&&<div className="alert alert-error">{error}</div>}{notice&&<div className="alert alert-success">{notice}</div>}

      {view==='overview'&&<>
        <section className="stats admin-stats"><div className="stat"><span>Total pendaftar</span><strong>{total}</strong><small>Seluruh data masuk</small></div><div className="stat warning"><span>Dokumen pending</span><strong>{req}</strong><small>Perlu diperiksa</small></div><div className="stat warning"><span>Pembayaran pending</span><strong>{pay}</strong><small>Perlu diverifikasi</small></div><div className="stat success"><span>Terverifikasi lengkap</span><strong>{verified}</strong><small>{total?Math.round(verified/total*100):0}% dari total</small></div></section>
        <section className="admin-grid-2">
          <div className="panel"><div className="panel-head"><div><h2>Antrean kerja</h2><p>Prioritas yang perlu ditangani panitia.</p></div></div><div className="queue-list"><button onClick={()=>{setStatusFilter('docs_pending');setView('participants')}}><span className="queue-icon">D</span><div><strong>Verifikasi dokumen</strong><small>Review STRA dan bukti pengalaman dari popup</small></div><em>{req}</em></button><button onClick={()=>{setStatusFilter('pay_pending');setView('participants')}}><span className="queue-icon">Rp</span><div><strong>Verifikasi pembayaran</strong><small>Review bukti transfer peserta</small></div><em>{pay}</em></button></div></div>
          <div className="panel"><div className="panel-head"><div><h2>Status pendaftaran</h2><p>Kondisi form peserta saat ini.</p></div></div><div className="form-state-card"><span className={`state-dot state-${settings?.registration_status}`}/><div><strong>{settings?.registration_status==='open'?'Pendaftaran dibuka':settings?.registration_status==='maintenance'?'Maintenance':settings?.registration_status==='scheduled'?'Terjadwal':'Pendaftaran ditutup'}</strong><small>Ditutup: {formatDate(settings?.registration_closes_at)}</small></div><button className="btn btn-secondary btn-small" onClick={()=>setView('settings')}>Atur</button></div></div>
        </section>
        <section className="panel"><div className="panel-head"><div><h2>Pendaftar terbaru</h2><p>Klik dokumen untuk review dan verifikasi dari popup.</p></div><button className="link-button" onClick={()=>setView('participants')}>Lihat semua →</button></div><RegistrationTable rows={rows.slice(0,10)} openDoc={openDoc} role={adminUser?.role}/></section>
      </>}

      {view==='participants'&&<section className="panel participants-panel"><div className="panel-head"><div><h2>Pendaftar</h2><p>Review dokumen langsung dari popup tanpa berpindah halaman.</p></div><div className="result-count">{filtered.length} data</div></div><div className="admin-filters"><div className="search-box"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, email, nomor, STRA, institusi..."/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Semua status</option><option value="docs_pending">Dokumen pending</option><option value="pay_pending">Pembayaran pending</option><option value="verified">Terverifikasi lengkap</option><option value="rejected">Ditolak</option></select><select value={modeFilter} onChange={e=>setModeFilter(e.target.value)}><option value="all">Semua mode</option><option value="Online">Online</option><option value="Offline">Offline</option></select></div><div className="table-tools"><div><strong>{filtered.length}</strong><span> data ditampilkan</span></div><div><button className="btn btn-secondary btn-small" onClick={printRows} disabled={!filtered.length}>Print</button>{['super_admin','event_admin'].includes(adminUser?.role)&&<button className="btn btn-brand-primary btn-small" onClick={exportXlsx} disabled={!filtered.length}>Export Excel (.xlsx)</button>}</div></div><RegistrationTable rows={filtered} openDoc={openDoc} openBilling={openBilling} role={adminUser?.role}/></section>}

      {view==='settings'&&settings&&<form onSubmit={saveSettings} className="panel settings-panel"><div className="panel-head"><div><h2>Buka, tutup, atau maintenance</h2><p>Proteksi berlaku di tampilan form dan endpoint submit.</p></div><span className={`status ${settings.registration_status==='open'?'status-ok':'status-pending'}`}>{settings.registration_status}</span></div><div className="settings-grid"><div className="field"><label>Status form</label><select name="registration_status" defaultValue={settings.registration_status}><option value="open">Dibuka</option><option value="closed">Ditutup</option><option value="scheduled">Terjadwal</option><option value="maintenance">Maintenance</option></select><small>Gunakan Maintenance untuk cutover sementara.</small></div><div className="field"><label>Dibuka mulai</label><input type="datetime-local" name="registration_opens_at" defaultValue={settings.registration_opens_at?settings.registration_opens_at.slice(0,16):''}/></div><div className="field"><label>Ditutup pada</label><input type="datetime-local" name="registration_closes_at" defaultValue={settings.registration_closes_at?settings.registration_closes_at.slice(0,16):''}/></div><div className="field"><label>Maintenance sampai</label><input type="datetime-local" name="maintenance_until" defaultValue={settings.maintenance_until?settings.maintenance_until.slice(0,16):''}/><small>Maksimal 48 jam disarankan.</small></div><div className="field span-2"><label>Pesan maintenance</label><textarea rows="4" name="maintenance_message" defaultValue={settings.maintenance_message||''}/></div></div><div className="settings-actions"><button className="btn btn-brand-primary">Simpan pengaturan</button></div></form>}

      {view==='access'&&accessSettings&&<section className="event-access-admin">
        <div className="access-admin-stats"><div className="stat"><span>Offline terverifikasi</span><strong>{offlineVerified}</strong><small>Eligible untuk QR check-in</small></div><div className="stat success"><span>Sudah check-in</span><strong>{checkedIn}</strong><small>dari {offlineVerified} peserta offline</small></div><div className="stat"><span>Online terverifikasi</span><strong>{onlineVerified}</strong><small>Eligible menerima akses Zoom</small></div></div>
        <form onSubmit={saveEventAccess} className="panel event-access-settings"><div className="panel-head"><div><h2>Publikasi akses pelaksanaan</h2><p>QR dan link hanya tampil kepada peserta yang sudah terverifikasi lengkap.</p></div></div>
          <div className="access-settings-grid"><section className="access-setting-card"><div className="access-setting-title"><span className="access-setting-icon">⌁</span><div><h3>Peserta Offline</h3><p>QR unik untuk validasi check-in di lokasi.</p></div></div><label className="switch-line"><input type="checkbox" name="offline_qr_enabled" defaultChecked={!!accessSettings.event?.offline_qr_enabled}/><span>Publikasikan QR check-in</span></label><div className="field"><label>Mulai tampil</label><input type="datetime-local" name="offline_qr_release_at" defaultValue={dateTimeLocal(accessSettings.event?.offline_qr_release_at)}/><small>Kosongkan untuk tampil segera setelah diaktifkan.</small></div><div className="access-setting-note">QR berisi token unik. Setelah discan, panitia melihat status peserta dari database dan mengonfirmasi check-in.</div></section>
          <section className="access-setting-card"><div className="access-setting-title"><span className="access-setting-icon">▶</span><div><h3>Peserta Online</h3><p>QR dan tombol untuk membuka Zoom Meeting.</p></div></div><label className="switch-line"><input type="checkbox" name="online_access_enabled" defaultChecked={!!accessSettings.event?.online_access_enabled}/><span>Publikasikan akses Zoom</span></label><div className="field"><label>Link Zoom</label><input type="url" name="zoom_url" defaultValue={accessSettings.event?.zoom_url||''} placeholder="https://...zoom.us/j/..."/></div><div className="field"><label>Mulai tampil</label><input type="datetime-local" name="online_access_release_at" defaultValue={dateTimeLocal(accessSettings.event?.online_access_release_at)}/><small>Link dan QR tidak dikirim ke peserta sebelum waktu ini.</small></div></section></div>
          {['super_admin','event_admin'].includes(adminUser?.role)?<div className="settings-actions"><button className="btn btn-brand-primary">Simpan akses acara</button><a className="btn btn-secondary" href="/admin/checkin">Buka halaman check-in ↗</a></div>:<div className="read-only-box">Role Anda dapat melihat pengaturan tetapi tidak dapat mengubahnya.</div>}
        </form>
      </section>}

      {view==='announcements'&&<section className="announcement-admin-grid"><form className="panel announcement-editor-panel" onSubmit={publishAnnouncement}><div className="panel-head"><div><h2>Buat pengumuman</h2><p>Pengumuman tampil di Dashboard Peserta dan dikirim melalui email.</p></div></div><div className="field"><label>Subject</label><input value={announcementSubject} onChange={e=>setAnnouncementSubject(e.target.value)} required maxLength="180" placeholder="Contoh: Informasi teknis pelaksanaan pelatihan"/></div><div className="field"><label>Penerima</label><select value={announcementAudience} onChange={e=>setAnnouncementAudience(e.target.value)}><option value="all">Semua peserta</option><option value="online">Peserta Online</option><option value="offline">Peserta Offline</option><option value="verified">Peserta terverifikasi</option></select></div><div className="field"><label>Isi pengumuman</label><div className="rich-editor"><div className="rich-toolbar"><button type="button" onClick={()=>editorCommand('bold')}><b>B</b></button><button type="button" onClick={()=>editorCommand('italic')}><i>I</i></button><button type="button" onClick={()=>editorCommand('underline')}><u>U</u></button><button type="button" onClick={()=>editorCommand('insertUnorderedList')}>• List</button><button type="button" onClick={()=>editorCommand('insertOrderedList')}>1. List</button><button type="button" onClick={()=>{const url=prompt('URL tautan');if(url)editorCommand('createLink',url)}}>Link</button></div><div ref={editorRef} className="rich-content" contentEditable suppressContentEditableWarning data-placeholder="Tulis isi pengumuman di sini..."/></div></div>{['super_admin','event_admin'].includes(adminUser?.role)?<button className="btn btn-brand-primary" disabled={announcementBusy}>{announcementBusy?'Mengirim...':'Publikasikan & kirim email'}</button>:<div className="read-only-box">Role Anda dapat melihat pengumuman, tetapi tidak dapat mempublikasikan.</div>}</form><div className="panel announcement-history"><div className="panel-head"><div><h2>Riwayat pengumuman</h2><p>{announcements.length} pengumuman telah dipublikasikan.</p></div></div>{!announcements.length?<div className="empty-state compact"><h3>Belum ada pengumuman</h3></div>:<div className="announcement-admin-list">{announcements.map(a=><article key={a.id}><div><strong>{a.subject}</strong><small>{formatDate(a.published_at)} · {a.audience}</small></div><span className="status status-info">Terkirim</span></article>)}</div>}</div></section>}

      {view==='team'&&adminUser?.role==='super_admin'&&<section className="admin-grid-team"><form onSubmit={addAdmin} className="panel"><div className="panel-head"><div><h2>Tambah panitia</h2><p>Undangan aktivasi password dikirim melalui Resend.</p></div></div><div className="field"><label>Nama</label><input name="display_name" placeholder="Nama panitia"/></div><div className="field"><label>Email</label><input name="email" type="email" required placeholder="nama@aptfi.or.id"/></div><div className="field"><label>Role</label><select name="role" defaultValue="viewer"><option value="event_admin">Admin Event</option><option value="document_verifier">Verifikator Dokumen</option><option value="payment_verifier">Verifikator Pembayaran</option><option value="viewer">Viewer</option><option value="super_admin">Super Admin</option></select></div><button className="btn btn-brand-primary">Simpan & kirim undangan</button></form><div className="panel"><div className="panel-head"><div><h2>Daftar akun</h2><p>{team.length} akun panitia terdaftar.</p></div></div><div className="team-list">{team.map(u=><div className="team-row" key={u.id}><div className="avatar">{(u.display_name||u.email).slice(0,1).toUpperCase()}</div><div className="team-info"><strong>{u.display_name||u.email}</strong><small>{u.email} · {roleLabel[u.role]||u.role}</small></div><span className={`status ${u.active?'status-ok':'status-bad'}`}>{u.active?'Aktif':'Nonaktif'}</span><button className="btn btn-secondary btn-small" onClick={()=>toggleAdmin(u)}>{u.active?'Nonaktifkan':'Aktifkan'}</button></div>)}</div></div></section>}
    </main>

    {docModal&&<DocumentModal modal={docModal} onClose={()=>setDocModal(null)} canReview={canReview(adminUser?.role,docModal.type)} onVerify={askVerify} onReject={askReject}/>} 
    {confirm&&<ReviewConfirm mode={confirm.mode} previousStatus={confirm.previousStatus} documentType={docModal?.type} reason={rejectReason} setReason={setRejectReason} nextAction={nextAction} setNextAction={setNextAction} busy={reviewBusy} onCancel={()=>setConfirm(null)} onSubmit={()=>submitReview(confirm.mode==='verify'?'valid':'rejected')}/>} 
  </div>
}

function canReview(role,type){return type==='payment_proof'?['super_admin','event_admin','payment_verifier'].includes(role):['super_admin','event_admin','document_verifier'].includes(role)}

function RegistrationTable({rows,openDoc,openBilling,role}){
  if(!rows.length)return <div className="empty-state"><div>⌕</div><h3>Tidak ada data</h3><p>Coba ubah kata kunci atau filter.</p></div>;
  return <div className="table-wrap"><table className="table admin-table"><thead><tr><th>Pendaftar</th><th>Mode</th><th>Persyaratan</th><th>Pembayaran</th><th>Dokumen Keuangan</th><th>Review dokumen</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><div className="participant-cell"><div className="avatar small">{r.full_name?.slice(0,1)?.toUpperCase()}</div><div><div className="participant-name-line"><strong>{r.full_name}</strong>{r.possible_duplicate&&<span className="duplicate-flag" title="Nama dan homebase mirip dengan pendaftar lain">Cek duplikat</span>}</div><small>{r.registration_code}</small><small>{displayParticipantEmail(r)}</small>{r.email_needs_update&&<span className="duplicate-flag" title="Email ini dipakai lebih dari satu peserta pada data WordPress. Tetapkan email unik sebelum aktivasi akun.">Email perlu diperbarui</span>}{r.stra_number&&<small>STRA: {r.stra_number}</small>}</div></div></td><td><span className="mode-chip">{r.attendance_mode||'—'}</span></td><td>{badge(r.requirements_status)}</td><td>{badge(r.payment_status)}</td><td><div className="billing-mini-actions"><button className="btn btn-secondary btn-small" onClick={()=>openBilling(r,'invoice')}>Tagihan</button><button className="btn btn-secondary btn-small" disabled={r.payment_status!=='verified'} onClick={()=>openBilling(r,'receipt')}>Kwitansi</button></div></td><td><div className="review-buttons">{['stra','experience','payment_proof'].map(type=>{const doc=r.documents?.[type];if(!doc)return null;return <button key={type} className={`review-doc-button ${docStatusClass(doc.status)}`} onClick={()=>openDoc(r,type)} title={`Review ${docLabel[type]}`}><span className="doc-dot"/><strong>{type==='stra'?'STRA':type==='experience'?'Pengalaman':'Pembayaran'}</strong><small>{doc.status==='valid'?'Valid':doc.status==='rejected'?'Ditolak':'Review'}</small></button>})}</div>{!['super_admin','event_admin','document_verifier','payment_verifier'].includes(role)&&<small className="muted">Akses read only</small>}</td></tr>)}</tbody></table></div>
}

function DocumentModal({modal,onClose,canReview,onVerify,onReject}){
  if(modal.loading)return <div className="modal-backdrop"><div className="document-modal loading-modal"><div className="spinner"/><p>Memuat dokumen...</p></div></div>;
  const d=modal.document||{};
  const isPdf=d.mime_type==='application/pdf'||String(d.original_name||'').toLowerCase().endsWith('.pdf');
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="document-modal"><header className="document-modal-header"><div><div className="eyebrow brand-blue">Review Dokumen</div><h2>{docLabel[modal.type]}</h2><p>{modal.row.full_name} · {modal.row.registration_code}</p></div><button className="modal-close" onClick={onClose} aria-label="Tutup">×</button></header><div className="document-modal-body"><div className="document-preview">{isPdf?<iframe title={docLabel[modal.type]} src={modal.url}/>:<img src={modal.url} alt={docLabel[modal.type]}/>}</div><aside className="review-panel"><div className="review-meta"><small>Status saat ini</small>{badge(d.status)}<div className="meta-row"><span>Nama file</span><strong>{d.original_name||'—'}</strong></div><div className="meta-row"><span>Diunggah</span><strong>{formatDate(d.created_at)}</strong></div>{d.review_note&&<div className="existing-review"><span>Catatan terakhir</span><p>{d.review_note}</p>{d.next_action&&<small>{d.next_action}</small>}</div>}</div>{canReview?<div className="review-actions"><p>Pastikan isi dokumen sesuai data peserta dan dapat dibaca dengan jelas.</p>{d.status==='valid'?<button className="btn btn-brand-primary btn-block" disabled>Sudah terverifikasi</button>:<button className="btn btn-brand-primary btn-block" onClick={onVerify}>Verifikasi dokumen</button>}{d.status==='rejected'?<button className="btn btn-danger btn-block" disabled>Sudah ditolak</button>:<button className="btn btn-danger btn-block" onClick={onReject}>{d.status==='valid'?'Ubah menjadi ditolak':'Tolak dokumen'}</button>}</div>:<div className="read-only-box">Akun Anda hanya dapat melihat dokumen ini.</div>}<a className="text-link center-link" href={modal.url} target="_blank" rel="noreferrer">Buka di tab baru ↗</a></aside></div></section></div>
}

function ReviewConfirm({mode,previousStatus,documentType,reason,setReason,nextAction,setNextAction,busy,onCancel,onSubmit}){
  const rejected=mode==='reject';
  return <div className="modal-backdrop modal-backdrop-top"><section className="confirm-modal"><div className={`confirm-symbol ${rejected?'danger':'success'}`}>{rejected?'!':'✓'}</div><h2>{rejected?'Tolak dokumen ini?':'Verifikasi dokumen ini?'}</h2>{rejected&&previousStatus==='valid'&&<div className="alert alert-warning">Dokumen ini sebelumnya sudah berstatus <strong>Valid</strong>. Perubahan akan tercatat pada audit log dan peserta akan menerima email.</div>}{!rejected?<p>Pastikan dokumen sudah dibaca dan sesuai. Status peserta akan langsung diperbarui setelah konfirmasi.</p>:<><p>Jelaskan alasan dengan spesifik agar peserta tahu apa yang harus diperbaiki. Peserta akan menerima catatan ini melalui email dan dashboard.</p><div className="field"><label>Alasan / catatan penolakan *</label><textarea rows="4" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Contoh: Foto STRA buram dan nomor tidak dapat dibaca."/></div><div className="field"><label>Langkah selanjutnya *</label><textarea rows="3" value={nextAction} onChange={e=>setNextAction(e.target.value)} placeholder="Contoh: Unggah ulang dokumen yang jelas melalui Dashboard Peserta."/></div><div className="email-notice">Email instruksi akan dikirim otomatis ke peserta setelah penolakan dikonfirmasi.</div></>}<div className="confirm-actions"><button className="btn btn-secondary" onClick={onCancel} disabled={busy}>Batal</button><button className={`btn ${rejected?'btn-danger':'btn-brand-primary'}`} onClick={onSubmit} disabled={busy||rejected&&(!reason.trim()||!nextAction.trim())}>{busy?'Memproses...':rejected?'Ya, tolak & kirim email':'Ya, verifikasi'}</button></div></section></div>
}

function escapePrint(value=''){return String(value??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[ch]))}
