'use client';
import FeedbackBridge from './FeedbackBridge';
import { useEffect,useState } from 'react';
import { getSupabaseBrowser } from '../lib/supabase-browser';
export default function MasterDataAdmin(){
  const [options,setOptions]=useState({}),[group,setGroup]=useState('practice_type'),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function token(){const {data}=await getSupabaseBrowser().auth.getSession();return data.session?.access_token||''}async function api(url,opts={}){const t=await token();const r=await fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Request gagal.');return j}async function load(){try{const j=await api('/api/admin/master-data');setOptions(j.options||{})}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
  async function save(e){e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));body.group_key=group;try{setBusy(true);setError('');if(editing){body.id=editing.id;await api('/api/admin/master-data',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice('Data master diperbarui.')}else{await api('/api/admin/master-data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice('Opsi baru ditambahkan.')}setEditing(null);form.reset();await load()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function toggle(item){try{setBusy(true);await api('/api/admin/master-data',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,active:!item.active})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const rows=options[group]||[];return <div className="master-data-layout"><FeedbackBridge notice={notice} error={error} onNotice={()=>setNotice('')}/><section className="panel master-data-panel"><div className="panel-head"><div><h2>Data Master Form</h2><p>Opsi nonaktif tidak muncul untuk pendaftar baru, tetapi data peserta lama tetap aman.</p></div></div><div className="master-tabs"><button className={group==='practice_type'?'active':''} onClick={()=>{setGroup('practice_type');setEditing(null)}}>Jenis Tempat Praktik</button><button className={group==='participant_type'?'active':''} onClick={()=>{setGroup('participant_type');setEditing(null)}}>Jenis Peserta</button></div><div className="master-data-rows">{rows.map(x=><article key={x.id} className={!x.active?'inactive':''}><div><strong>{x.label}</strong><small>Key: {x.value}{group==='practice_type'&&x.min_years!=null?` · minimal ${Number(x.min_years)} tahun`:''} · urutan {x.sort_order}</small></div><div><span className={`status ${x.active?'status-ok':'status-bad'}`}>{x.active?'Aktif':'Nonaktif'}</span><button className="btn btn-secondary btn-small" onClick={()=>setEditing(x)}>Edit</button><button className="btn btn-secondary btn-small" onClick={()=>toggle(x)} disabled={busy}>{x.active?'Nonaktifkan':'Aktifkan'}</button></div></article>)}</div></section>
    <form className="panel master-data-form" onSubmit={save}><div className="panel-head"><div><h2>{editing?'Edit opsi':group==='practice_type'?'Tambah jenis tempat praktik':'Jenis peserta sistem'}</h2><p>{group==='participant_type'&&!editing?'Jenis peserta memiliki perilaku sistem sehingga key baru tidak dapat ditambahkan. Label, urutan, dan status tetap dapat diedit.':'Atur label, minimum pengalaman, dan urutan pilihan.'}</p></div></div>{(group==='practice_type'||editing)&&<><div className="field"><label>Label</label><input key={`label-${editing?.id||'new'}`} name="label" required defaultValue={editing?.label||''}/></div>{!editing&&group==='practice_type'&&<div className="field"><label>Value / key</label><input name="value" required placeholder="Contoh: Klinik"/><small>Jangan diubah setelah mulai digunakan peserta.</small></div>}<div className="field"><label>Urutan</label><input key={`sort-${editing?.id||'new'}`} name="sort_order" type="number" defaultValue={editing?.sort_order??100}/></div>{group==='practice_type'&&<div className="field"><label>Minimal pengalaman (tahun)</label><input key={`min-${editing?.id||'new'}`} name="min_years" type="number" min="0" step="0.5" defaultValue={editing?.min_years??''}/></div>}<div className="master-form-actions"><button className="btn btn-brand-primary" disabled={busy}>{busy?'Menyimpan...':editing?'Simpan perubahan':'Tambah opsi'}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={()=>setEditing(null)}>Batal</button>}</div></>}</form></div>
}
