'use client';
import FeedbackBridge from './FeedbackBridge';
import { useEffect,useRef,useState } from 'react';
import { getSupabaseBrowser } from '../lib/supabase-browser';
import { fileMeta, parseApiResponse, uploadSignedFiles } from '../lib/direct-upload-client';
import ParticipantProfile from './ParticipantProfile';
import AssessmentParticipantPanel from './AssessmentParticipantPanel';
import { ParticipantSidebar,ParticipantTopbar,ParticipantTabbar,navMarkers } from './ParticipantNav';

const statusLabel={incomplete:'Perlu dilengkapi',pending:'Menunggu verifikasi',valid:'Valid',rejected:'Perlu perbaikan',verified:'Terverifikasi'};
function statusClass(v){return ['valid','verified'].includes(v)?'status-ok':v==='rejected'?'status-bad':'status-pending'}
function docLabel(type){return type==='stra'?'STRA':type==='experience'?'Bukti pengalaman':'Bukti pembayaran'}
function fmtDate(v){if(!v)return '';try{return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v))}catch{return v}}

export default function ParticipantDashboard(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[type,setType]=useState('');
  const [tab,setTab]=useState('registration'),[announcements,setAnnouncements]=useState([]),[unreadCount,setUnreadCount]=useState(0),[selectedAnnouncement,setSelectedAnnouncement]=useState(null);
  const [eventAccess,setEventAccess]=useState(null),[accessLoading,setAccessLoading]=useState(false),[dayH,setDayH]=useState(null),[dayHLoading,setDayHLoading]=useState(false),[assessments,setAssessments]=useState({}),[assessmentLoading,setAssessmentLoading]=useState({}),[billingModal,setBillingModal]=useState(null),[master,setMaster]=useState({practice_type:[],participant_type:[]});
  const [participantNavCollapsed,setParticipantNavCollapsed]=useState(false),[participantMobileNavOpen,setParticipantMobileNavOpen]=useState(false),[navSummary,setNavSummary]=useState(null);
  const billingCache=useRef(new Map());
  async function token(){const {data}=await getSupabaseBrowser().auth.getSession();return data.session?.access_token||''}
  async function loadAnnouncements(){const t=await token();if(!t)return;const r=await fetch('/api/me/announcements',{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok){setAnnouncements(j.announcements||[]);setUnreadCount(j.unreadCount||0)}}
  async function loadSummary(){try{const t=await token();if(!t)return;const r=await fetch('/api/me/summary',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});if(r.ok)setNavSummary(await r.json())}catch{}}
  async function loadDayH(){const t=await token();if(!t)return;setDayHLoading(true);const r=await fetch('/api/me/day-h',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setDayH(j);setDayHLoading(false)}
  async function loadAssessment(kind){const t=await token();if(!t)return;setAssessmentLoading(v=>({...v,[kind]:true}));try{const r=await fetch(`/api/me/${kind}`,{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setAssessments(v=>({...v,[kind]:j}));else setError(j.message||'Data assessment gagal dimuat.')}catch{setError('Koneksi bermasalah. Coba muat ulang.')}finally{setAssessmentLoading(v=>({...v,[kind]:false}))}}
  function loadTabData(next){if(next==='attendance')loadDayH();if(['pretest','evaluation','posttest'].includes(next))loadAssessment(next);if(next==='access')loadEventAccess()}
  async function loadEventAccess(){const t=await token();if(!t)return;setAccessLoading(true);const r=await fetch('/api/me/event-access',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setEventAccess(j);setAccessLoading(false)}
  async function load(){const t=await token();if(!t){location.href='/login';return}const [r,m]=await Promise.all([fetch('/api/me/registrations',{headers:{Authorization:`Bearer ${t}`}}),fetch('/api/master-data').catch(()=>null)]);const j=await r.json();if(!r.ok)setError(j.message);else{setData(j.registration);setType(j.registration?.participant_type||'')}if(m?.ok){const mj=await m.json();setMaster(mj.options||{})}await Promise.all([loadAnnouncements(),loadEventAccess(),loadSummary()])}
  useEffect(()=>{const requested=new URLSearchParams(location.search).get('tab');if(['profile','announcements','attendance','pretest','evaluation','posttest','access'].includes(requested)){setTab(requested);loadTabData(requested)}setParticipantNavCollapsed(localStorage.getItem('aptfi-participant-sidebar-collapsed')==='1');load();return()=>{for(const item of billingCache.current.values()){if(item?.url)URL.revokeObjectURL(item.url)}}},[]);
  useEffect(()=>{if(!participantMobileNavOpen)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const closeOnEscape=e=>{if(e.key==='Escape')setParticipantMobileNavOpen(false)};window.addEventListener('keydown',closeOnEscape);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',closeOnEscape)}},[participantMobileNavOpen]);
  function selectParticipantTab(next){setTab(next);setParticipantMobileNavOpen(false);loadTabData(next);loadSummary();try{window.scrollTo({top:0,behavior:'smooth'})}catch{}}
  async function complete(e){
    e.preventDefault();
    const form=e.currentTarget;
    setBusy(true);setError('');setNotice('');
    try{
      const t=await token(),fd=new FormData(form);
      const fileMap={stra:fd.get('stra_proof'),experience:fd.get('experience_proof')};
      const files=Object.fromEntries(Object.entries(fileMap).map(([k,f])=>[k,fileMeta(f)]).filter(([,v])=>v));
      let uploaded={};
      if(Object.keys(files).length){
        const pr=await fetch('/api/me/uploads/prepare',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({purpose:'requirements',files})});
        const pj=await parseApiResponse(pr);if(!pr.ok)throw new Error(pj.message||'Gagal menyiapkan unggahan.');
        await uploadSignedFiles(pj.uploads,fileMap);uploaded=pj.uploads;
      }
      const payload={stra_number:fd.get('stra_number'),participant_type:fd.get('participant_type'),practice_type:fd.get('practice_type'),practice_name:fd.get('practice_name'),practice_years:fd.get('practice_years'),teaching_years:fd.get('teaching_years'),files:uploaded};
      const r=await fetch('/api/me/requirements',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await parseApiResponse(r);if(!r.ok)throw new Error(j.message||'Gagal menyimpan dokumen.');
      setNotice('Dokumen persyaratan berhasil dikirim ulang dan menunggu verifikasi.');await load();
    }catch(err){setError(err?.message==='Failed to fetch'?'Koneksi terputus saat mengunggah dokumen. Silakan coba lagi dengan koneksi yang stabil.':(err?.message||'Gagal mengunggah dokumen.'))}finally{setBusy(false)}
  }
  async function reuploadPayment(e){
    e.preventDefault();
    const form=e.currentTarget;
    setBusy(true);setError('');setNotice('');
    try{
      const t=await token(),fd=new FormData(form),file=fd.get('payment_proof');
      const pr=await fetch('/api/me/uploads/prepare',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({purpose:'payment',files:{payment_proof:fileMeta(file)}})});const pj=await parseApiResponse(pr);if(!pr.ok)throw new Error(pj.message||'Gagal menyiapkan unggahan.');
      await uploadSignedFiles(pj.uploads,{payment_proof:file});
      const r=await fetch('/api/me/payment',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({files:pj.uploads})});const j=await parseApiResponse(r);if(!r.ok)throw new Error(j.message||'Gagal menyimpan bukti pembayaran.');
      const isInitialPayment=!data?.documents?.payment_proof;
      setNotice(isInitialPayment?'Bukti pembayaran berhasil dikirim dan menunggu verifikasi.':'Bukti pembayaran berhasil dikirim ulang dan menunggu verifikasi.');await load();
    }catch(err){setError(err?.message==='Failed to fetch'?'Koneksi terputus saat mengunggah bukti pembayaran. Silakan coba lagi.':(err?.message||'Gagal mengunggah bukti pembayaran.'))}finally{setBusy(false)}
  }
  async function openBilling(kind){try{setError('');const cached=billingCache.current.get(kind);if(cached?.url){setBillingModal({loading:false,kind,url:cached.url});return}setBillingModal({loading:true,kind});const t=await token();const r=await fetch(`/api/billing/${kind}?id=${data.id}`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.message||'Dokumen belum tersedia.')}const blob=await r.blob();const url=URL.createObjectURL(blob);billingCache.current.set(kind,{url});setBillingModal({loading:false,kind,url})}catch(e){setBillingModal(null);setError(e.message)}}
  async function openAnnouncement(a){setSelectedAnnouncement(a);if(!a.is_read){const t=await token();await fetch('/api/me/announcements',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({announcementId:a.id})});setAnnouncements(list=>list.map(x=>x.id===a.id?{...x,is_read:true,read_at:new Date().toISOString()}:x));setUnreadCount(v=>Math.max(0,v-1))}}
  async function logout(){await getSupabaseBrowser().auth.signOut();location.href='/'}
  if(!data&&!error)return <main className="participant-shell"><div className="participant-appbar"><img src="/aptfi-logo.png" alt="APTFI"/></div><div className="participant-loading"><div className="spinner"/><p>Memuat pendaftaran...</p></div></main>;
  if(error&&!data)return <main className="participant-shell"><div className="alert alert-error">{error}</div><a className="btn btn-secondary" href="/login">Kembali ke login</a></main>;

  const practitioner=['practitioner','lecturer_practitioner'].includes(type),lecturer=['lecturer','lecturer_practitioner'].includes(type);
  const isTest=!!data.is_test_account;
  const withdrawn=data.lifecycle_status==='withdrawn';
  const registrationRejected=data.lifecycle_status==='rejected';
  const inactive=withdrawn||registrationRejected;
  const completeStatus=!inactive&&data.requirements_status==='valid'&&data.payment_status==='verified';
  const docs=data.documents||{};
  const missingRequirements=['stra','experience'].filter(k=>!docs[k]);
  const rejectedRequirements=['stra','experience'].filter(k=>docs[k]?.status==='rejected');
  const paymentRejected=data.payment_status==='rejected';
  const paymentMissing=!docs.payment_proof;
  const requirementsNeedAction=!isTest&&!inactive&&(['incomplete','rejected'].includes(data.requirements_status)||missingRequirements.length>0);
  const paymentNeedsUpload=!isTest&&!inactive&&(paymentRejected||(data.payment_status==='pending'&&paymentMissing));
  const requirementsDisplayStatus=(data.requirements_status==='pending'&&missingRequirements.length>0)?'incomplete':data.requirements_status;
  const paymentDisplayStatus=(data.payment_status==='pending'&&paymentMissing)?'incomplete':data.payment_status;
  const requirementsCaption=isTest?'Disimulasikan untuk akun uji':missingRequirements.length?'Dokumen persyaratan belum lengkap':'STRA & bukti pengalaman';
  const paymentCaption=isTest?'Disimulasikan untuk akun uji':paymentMissing?'Bukti transfer belum diunggah':'Bukti transfer';
  const finalCaption=isTest?'Akun siap untuk simulasi':'Konfirmasi akhir peserta';

  return <main className="participant-page participant-page-with-sidebar app-shell-page"><div className={`app-shell ${participantNavCollapsed?'collapsed':''}`}>
    <ParticipantSidebar tab={tab} select={selectParticipantTab} data={data} summary={navSummary} markers={navMarkers(data,navSummary)} unreadCount={unreadCount} collapsed={participantNavCollapsed} toggleCollapsed={()=>setParticipantNavCollapsed(v=>{const n=!v;localStorage.setItem('aptfi-participant-sidebar-collapsed',n?'1':'0');return n})} open={participantMobileNavOpen} close={()=>setParticipantMobileNavOpen(false)} logout={logout}/>
    <div className="participant-shell participant-shell-sidebar">
    <ParticipantTopbar tab={tab} unreadCount={unreadCount} openAnnouncements={()=>selectParticipantTab('announcements')}/>
    <div className="participant-welcome"><span>Halo,</span><h1>{data.full_name}</h1></div>
    <FeedbackBridge notice={notice} error={error} onNotice={()=>setNotice('')}/>{isTest&&<div className="alert alert-info"><strong>Mode Akun Uji.</strong> Akun ini tidak masuk kuota, statistik, atau laporan resmi.</div>}

    {tab==='profile'?<ParticipantProfile initialRegistration={data} onChanged={load}/>:tab==='announcements'?<AnnouncementPanel announcements={announcements} unreadCount={unreadCount} selectedAnnouncement={selectedAnnouncement} openAnnouncement={openAnnouncement} close={()=>setSelectedAnnouncement(null)}/>:tab==='attendance'?<DayHParticipantPanel data={dayH} loading={dayHLoading} refresh={loadDayH} token={token}/>:['pretest','evaluation','posttest'].includes(tab)?<AssessmentParticipantPanel key={tab} kind={tab} data={assessments[tab]} loading={!!assessmentLoading[tab]} refresh={()=>loadAssessment(tab)} token={token} onOpenAttendance={()=>selectParticipantTab('attendance')}/>:tab==='access'?<EventAccessPanel access={eventAccess} loading={accessLoading} refresh={loadEventAccess}/>:<>
      <section className={`participant-status-hero ${completeStatus?'complete':''} ${inactive?'withdrawn':''}`}><div><div className="eyebrow light">Status Pendaftaran</div><h2>{registrationRejected?'Pendaftaran ditolak':withdrawn?'Mengundurkan diri':completeStatus?'Pendaftaran terverifikasi':'Pendaftaran sedang diproses'}</h2><p>{registrationRejected?`Pendaftaran Anda telah ditolak oleh panitia.${data.rejected_reason?` Alasan: ${data.rejected_reason}`:''} ${data.payment_status==='verified'?'Anda masih dapat mengajukan refund melalui Profil Saya.':''}`:withdrawn?'Pendaftaran Anda telah berstatus mengundurkan diri. Pantau proses refund melalui Profil Saya bila Anda mengajukannya.':completeStatus?'Persyaratan dan pembayaran Anda sudah terverifikasi oleh panitia.':'Pantau progres verifikasi di halaman ini. Jika ada perbaikan, instruksinya akan ditampilkan di bawah.'}</p></div><div className="registration-code"><span>Nomor pendaftaran</span><strong>{data.registration_code}</strong></div></section>
      <section className="participant-progress"><div className={`progress-card ${statusClass(requirementsDisplayStatus)}`}><div className="progress-icon">1</div><div><span>Persyaratan</span><strong>{statusLabel[requirementsDisplayStatus]||requirementsDisplayStatus}</strong><small>{requirementsCaption}</small></div></div><div className={`progress-card ${statusClass(paymentDisplayStatus)}`}><div className="progress-icon">2</div><div><span>Pembayaran</span><strong>{statusLabel[paymentDisplayStatus]||paymentDisplayStatus}</strong><small>{paymentCaption}</small></div></div><div className={`progress-card ${completeStatus?'status-ok':'status-pending'}`}><div className="progress-icon">3</div><div><span>Status akhir</span><strong>{completeStatus?'Terverifikasi':'Dalam proses'}</strong><small>{finalCaption}</small></div></div></section>

      {!isTest&&<section className="participant-card billing-card"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Dokumen Keuangan</div><h2>Tagihan & Kwitansi</h2><p>Tagihan tersedia sejak pendaftaran. Kwitansi diterbitkan setelah pembayaran terverifikasi.</p></div></div><div className="billing-actions"><button className="billing-document" onClick={()=>openBilling('invoice')}><span className="billing-icon">↓</span><span><strong>Tagihan / Invoice</strong><small>PDF · Rp 1.000.000</small></span></button><button className={`billing-document ${data.payment_status!=='verified'?'disabled':''}`} disabled={data.payment_status!=='verified'} onClick={()=>openBilling('receipt')}><span className="billing-icon">✓</span><span><strong>Kwitansi</strong><small>{data.payment_status==='verified'?'PDF · pembayaran terverifikasi':'Tersedia setelah verifikasi'}</small></span></button></div></section>}

      {completeStatus&&<section className="participant-card access-teaser"><div><div className="eyebrow brand-blue">Akses Pelaksanaan</div><h2>{data.attendance_mode==='Offline'?'QR check-in lokasi':'Akses Zoom'}</h2><p>Akses acara akan tersedia pada waktu yang ditentukan panitia.</p></div><button className="btn btn-brand-primary" onClick={()=>{setTab('access');loadEventAccess()}}>Lihat Akses Acara</button></section>}

      {rejectedRequirements.map(key=><section className="participant-card rejection-card" key={key}><div className="rejection-icon">!</div><div><div className="eyebrow danger-text">Perlu diperbaiki</div><h2>{docLabel(key)} ditolak</h2><p><strong>Catatan panitia:</strong> {docs[key]?.review_note||'Silakan periksa kembali dokumen.'}</p><p><strong>Langkah selanjutnya:</strong> {docs[key]?.next_action||'Unggah dokumen yang benar melalui form di bawah.'}</p></div></section>)}
      {paymentRejected&&<section className="participant-card rejection-card"><div className="rejection-icon">!</div><div><div className="eyebrow danger-text">Perlu diperbaiki</div><h2>Bukti pembayaran ditolak</h2><p><strong>Catatan panitia:</strong> {docs.payment_proof?.review_note||'Silakan periksa kembali bukti pembayaran.'}</p><p><strong>Langkah selanjutnya:</strong> {docs.payment_proof?.next_action||'Unggah ulang bukti pembayaran melalui form di bawah.'}</p></div></section>}

      <section className="participant-card"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Ringkasan</div><h2>Data Pendaftaran</h2></div><span className="mode-chip">{data.attendance_mode||'—'}</span></div><div className="participant-details"><div><span>Email</span><strong>{data.email}</strong></div><div><span>WhatsApp</span><strong>{data.whatsapp||'—'}</strong></div><div><span>Nomor STRA</span><strong>{data.stra_number||'Belum dilengkapi'}</strong></div><div><span>Homebase</span><strong>{data.university||'—'}</strong></div><div><span>Mode keikutsertaan</span><strong>{data.attendance_mode||'—'}</strong></div></div></section>

      {requirementsNeedAction&&<form onSubmit={complete} className="participant-card requirement-form"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Perlu tindakan</div><h2>{data.requirements_status==='rejected'?'Perbaiki Dokumen Persyaratan':'Lengkapi Persyaratan'}</h2><p>{data.requirements_status==='rejected'?'Dokumen yang tidak bermasalah tidak perlu diunggah ulang.':'Lengkapi data profesional, STRA, dan bukti pengalaman agar panitia dapat melakukan verifikasi.'}</p></div><span className="status status-bad">{data.requirements_status==='rejected'?'Perlu perbaikan':'Perlu dilengkapi'}</span></div><div className="field"><label>Nomor STRA</label><input name="stra_number" defaultValue={data.stra_number||''} required placeholder="Masukkan nomor STRA"/></div><div className="field"><label>Kategori peserta</label><select name="participant_type" value={type} onChange={e=>setType(e.target.value)} required><option value="">Pilih kategori</option>{(master.participant_type||[]).filter(x=>x.active!==false||x.value===type).map(x=><option key={x.id||x.value} value={x.value}>{x.label}</option>)}</select></div>{practitioner&&<div className="grid grid-3"><div className="field"><label>Jenis tempat praktik</label><select name="practice_type" defaultValue={data.practice_type||''} required><option value="">Pilih</option>{(master.practice_type||[]).filter(x=>x.active!==false||x.value===data.practice_type).map(x=><option key={x.id||x.value} value={x.value}>{x.label}{x.min_years?` · min ${Number(x.min_years)} th`:''}</option>)}</select></div><div className="field"><label>Nama tempat praktik</label><input name="practice_name" defaultValue={data.practice_name||''} required/></div><div className="field"><label>Lama praktik (tahun)</label><input name="practice_years" defaultValue={data.practice_years||''} type="number" min="0" step="0.5" required/></div></div>}{lecturer&&<div className="field"><label>Lama mengajar (tahun)</label><input name="teaching_years" defaultValue={data.teaching_years||''} type="number" min="0" step="0.5" required/></div>}<div className="grid grid-2">{(!docs.stra||docs.stra.status==='rejected')&&<div className="field upload modern-upload"><label>Bukti STRA</label><small>PDF/JPG/PNG · maks. 5 MB</small><input type="file" name="stra_proof" accept="image/jpeg,image/png,application/pdf" required/></div>}{(!docs.experience||docs.experience.status==='rejected')&&<div className="field upload modern-upload"><label>Bukti pengalaman</label><small>Surat keterangan, SK, atau dokumen relevan.</small><input type="file" name="experience_proof" accept="image/jpeg,image/png,application/pdf" required/></div>}</div><button className="btn btn-brand-primary btn-block-mobile" disabled={busy}>{busy?'Menyimpan...':data.requirements_status==='rejected'?'Kirim Perbaikan Dokumen':'Kirim Dokumen Persyaratan'}</button></form>}
      {paymentNeedsUpload&&<form onSubmit={reuploadPayment} className="participant-card payment-reupload"><div className="participant-card-head"><div><div className="eyebrow brand-blue">{paymentRejected?'Perbaikan Pembayaran':'Perlu tindakan'}</div><h2>{paymentRejected?'Unggah ulang bukti pembayaran':'Unggah bukti pembayaran'}</h2><p>{paymentRejected?'Gunakan bukti transfer yang sesuai dengan arahan panitia.':'Bukti pembayaran belum ada pada akun Anda. Unggah bukti transfer agar pembayaran dapat diverifikasi panitia.'}</p></div><span className="status status-bad">{paymentRejected?'Perlu perbaikan':'Belum dilengkapi'}</span></div><div className="field upload modern-upload"><label>{paymentRejected?'Bukti pembayaran baru':'Bukti pembayaran'}</label><small>PDF/JPG/PNG · maks. 5 MB</small><input type="file" name="payment_proof" accept="image/jpeg,image/png,application/pdf" required/></div><button className="btn btn-brand-primary" disabled={busy}>{busy?'Mengunggah...':paymentRejected?'Kirim Ulang Bukti Pembayaran':'Kirim Bukti Pembayaran'}</button></form>}
      {inactive&&<section className="participant-card info-card"><div className="info-icon">i</div><div><h3>{registrationRejected?'Pendaftaran tidak aktif karena ditolak':'Pendaftaran sudah ditutup untuk akun ini'}</h3><p>Data historis tetap tersimpan. Buka <strong>Profil Saya</strong> untuk melihat status dan {data.payment_status==='verified'?'mengajukan atau memantau refund.':'riwayat pendaftaran.'}</p></div></section>}
      {!inactive&&!requirementsNeedAction&&<section className="participant-card info-card"><div className="info-icon">✓</div><div><h3>{isTest?'Akun uji siap digunakan':'Dokumen sudah diterima'}</h3><p>{isTest?'Persyaratan dan pembayaran disimulasikan terverifikasi agar alur pelaksanaan dapat diuji tanpa dokumen resmi.':data.requirements_status==='valid'?'Dokumen persyaratan telah dinyatakan valid oleh panitia.':'Dokumen Anda sedang diperiksa oleh panitia.'}</p></div></section>}
    </>}
    <footer className="participant-footer"><span>APTFI · Pelatihan Preseptor 2026</span><a href="/">Beranda</a></footer>
    {billingModal&&<ParticipantBillingModal modal={billingModal} registrationCode={data.registration_code} onClose={()=>setBillingModal(null)}/>}
  </div></div><ParticipantTabbar tab={tab} select={selectParticipantTab} openMenu={()=>setParticipantMobileNavOpen(true)} unreadCount={unreadCount} markers={navMarkers(data,navSummary)}/></main>
}


function ParticipantBillingModal({modal,registrationCode,onClose}){
  const title=modal.kind==='receipt'?'Kwitansi Pembayaran':'Tagihan / Invoice';
  if(modal.loading)return <div className="modal-backdrop"><div className="billing-modal loading-modal"><div className="spinner"/><p>Menyiapkan {title.toLowerCase()}...</p><small>Dokumen akan tampil di halaman ini.</small></div></div>;
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="billing-modal participant-billing-modal"><header className="document-modal-header"><div><div className="eyebrow brand-blue">Dokumen Keuangan</div><h2>{title}</h2><p>{registrationCode}</p></div><button className="modal-close" onClick={onClose} aria-label="Tutup">×</button></header><div className="billing-preview"><iframe title={title} src={modal.url}/></div><footer className="billing-modal-actions"><a className="btn btn-secondary" href={modal.url} target="_blank" rel="noreferrer">Buka tab baru ↗</a><a className="btn btn-brand-primary" href={modal.url} download={`${modal.kind==='receipt'?'kwitansi':'tagihan'}-${registrationCode}.pdf`}>Unduh PDF</a></footer></section></div>
}

function AnnouncementPanel({announcements,unreadCount,selectedAnnouncement,openAnnouncement,close}){
  return <section className="participant-card announcement-center"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Informasi Panitia</div><h2>Pengumuman</h2><p>Klik subject untuk membaca isi pengumuman.</p></div>{unreadCount>0&&<span className="status status-info">{unreadCount} baru</span>}</div>{!announcements.length?<div className="empty-state compact"><h3>Belum ada pengumuman</h3><p>Informasi terbaru dari panitia akan tampil di sini.</p></div>:<div className="announcement-list">{announcements.map(a=><button key={a.id} className={`announcement-subject ${a.is_read?'read':'unread'}`} onClick={()=>openAnnouncement(a)}><span className="announcement-dot"/><span><strong>{a.subject}</strong><small>{fmtDate(a.published_at)}</small></span><b>›</b></button>)}</div>}{selectedAnnouncement&&<article className="announcement-detail"><button className="announcement-detail-close" onClick={close}>×</button><div className="eyebrow brand-blue">Pengumuman</div><h2>{selectedAnnouncement.subject}</h2><small>{fmtDate(selectedAnnouncement.published_at)}</small><div className="announcement-rich" dangerouslySetInnerHTML={{__html:selectedAnnouncement.body_html}}/></article>}</section>
}

function DayHParticipantPanel({data,loading,refresh,token}){
  const [busy,setBusy]=useState(''),[message,setMessage]=useState(''),[localError,setLocalError]=useState('');
  async function checkin(dayId){try{setBusy(dayId);setLocalError('');setMessage('');const t=await token();const r=await fetch('/api/me/day-h',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({dayId})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Presensi gagal.');setMessage('Presensi berhasil dicatat.');await refresh()}catch(e){setLocalError(e.message)}finally{setBusy('')}}
  if(loading&&!data)return <section className="participant-card"><div className="participant-loading compact"><div className="spinner"/><p>Memuat kehadiran...</p></div></section>;
  if(!data)return <section className="participant-card"><div className="empty-state compact"><h3>Data kehadiran belum tersedia</h3><button className="btn btn-secondary" onClick={refresh}>Muat ulang</button></div></section>;
  if(!data.enabled)return <section className="participant-card dayh-participant locked"><div className="access-lock">◷</div><h2>Presensi belum diaktifkan</h2><p>Menu akan aktif pada waktu yang ditentukan panitia.</p></section>;
  if(!data.eligible)return <section className="participant-card dayh-participant locked"><div className="access-lock">🔒</div><h2>Belum memenuhi syarat</h2><p>Presensi tersedia setelah dokumen valid dan pembayaran terverifikasi.</p></section>;
  return <section className="participant-card dayh-participant"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Kehadiran</div><h2>Presensi Harian</h2><p>{data.testAccount?'Mode TEST: waktu presensi dibypass, tetapi urutan check-in tetap diuji.':data.mode==='Online'?'Check-in mandiri tersedia pukul 07.00–09.00 WIB sesuai jadwal panitia.':'Tunjukkan QR kepada panitia di lokasi.'}</p></div>{data.testAccount&&<span className="status status-info">TEST</span>}</div><FeedbackBridge notice={message} onNotice={()=>setMessage('')}/>{localError&&<div className="alert alert-error">{localError}</div>}<div className="participant-day-list">{(data.days||[]).map(day=><article key={day.id}><div className="participant-day-head"><div><strong>{day.title}</strong><small>{new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date(`${day.event_date}T12:00:00+07:00`))}</small></div>{day.checkin?<span className="status status-ok">Hadir</span>:<span className="status status-pending">Belum hadir</span>}</div><div className="participant-attendance-times"><div><span>Check-in</span><strong>{day.checkin?`${fmtDate(day.checkin.occurred_at)} WIB`:'—'}</strong></div><div><span>Window</span><strong>{day.checkinState==='open'?'Dibuka':day.checkinState==='upcoming'?'Belum dibuka':'Ditutup'}</strong></div></div>{!day.checkin&&data.mode==='Online'&&<div className="participant-day-actions"><button className="btn btn-brand-primary" disabled={day.checkinState!=='open'||!!busy} onClick={()=>checkin(day.id)}>{busy===day.id?'Menyimpan...':day.checkinState==='open'?'Check-in Sekarang':'Belum tersedia'}</button></div>}{!day.checkin&&data.mode==='Offline'&&day.qrDataUrl&&<div className="dayh-offline-qr"><img src={day.qrDataUrl} alt={`QR presensi ${day.title}`}/><p>Tunjukkan QR ini kepada panitia.</p></div>}</article>)}</div></section>
}

function EventAccessPanel({access,loading,refresh}){
  if(loading&&!access)return <section className="participant-card event-access-card"><div className="participant-loading compact"><div className="spinner"/><p>Memuat akses acara...</p></div></section>;
  if(!access)return <section className="participant-card event-access-card"><div className="empty-state compact"><h3>Akses belum tersedia</h3><p>Silakan coba kembali beberapa saat lagi.</p><button className="btn btn-secondary" onClick={refresh}>Muat ulang</button></div></section>;
  if(access.rejected)return <section className="participant-card event-access-card locked"><div className="access-lock">🔒</div><div className="eyebrow brand-blue">Akses Acara</div><h2>Akses dinonaktifkan</h2><p>Pendaftaran Anda sudah ditolak oleh panitia.</p></section>;
  if(access.withdrawn)return <section className="participant-card event-access-card locked"><div className="access-lock">🔒</div><div className="eyebrow brand-blue">Akses Acara</div><h2>Akses dinonaktifkan</h2><p>Pendaftaran Anda sudah berstatus mengundurkan diri.</p></section>;
  if(!access.eligible)return <section className="participant-card event-access-card locked"><div className="access-lock">🔒</div><div className="eyebrow brand-blue">Akses Acara</div><h2>Menunggu verifikasi lengkap</h2><p>QR atau akses Zoom hanya tersedia untuk peserta dengan persyaratan <strong>Valid</strong> dan pembayaran <strong>Terverifikasi</strong>.</p></section>;
  const future=access.releaseAt&&!access.released;
  if(!access.available)return <section className="participant-card event-access-card scheduled"><div className="access-lock">◷</div><div className="eyebrow brand-blue">{access.mode==='Offline'?'QR Check-in':'Akses Zoom'}</div><h2>{!access.enabled?'Belum dipublikasikan':'Akses akan segera tersedia'}</h2><p>{future?`Panitia menjadwalkan akses mulai ${fmtDate(access.releaseAt)} WIB.`:'Panitia belum mempublikasikan akses. Informasi akan muncul otomatis di halaman ini ketika sudah tersedia.'}</p><button className="btn btn-secondary" onClick={refresh}>Periksa kembali</button></section>;
  if(access.kind==='offline')return <section className="participant-card event-access-card available"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Akses Peserta Offline</div><h2>QR Check-in Lokasi</h2><p>Tunjukkan QR ini kepada panitia saat tiba di lokasi. QR diverifikasi langsung ke sistem APTFI.</p></div><span className={`status ${access.checkedInAt?'status-ok':'status-info'}`}>{access.checkedInAt?'Sudah check-in':'Siap digunakan'}</span></div><div className="event-access-grid"><div className="qr-frame"><img src={access.qrDataUrl} alt="QR Check-in APTFI"/></div><div className="access-instructions"><strong>Petunjuk</strong><ol><li>Buka halaman ini saat tiba di lokasi.</li><li>Tunjukkan QR kepada panitia.</li><li>Panitia memindai QR dan memvalidasi status secara online.</li></ol>{access.checkedInAt&&<div className="checked-in-box"><span>Check-in tercatat</span><strong>{fmtDate(access.checkedInAt)} WIB</strong></div>}<small>Jangan bagikan QR kepada peserta lain. QR terhubung dengan pendaftaran Anda.</small></div></div></section>;
  return <section className="participant-card event-access-card available"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Akses Peserta Online</div><h2>Join Zoom Meeting</h2><p>Scan QR dari perangkat lain atau gunakan tombol di bawah untuk membuka Zoom.</p></div><span className="status status-ok">Tersedia</span></div><div className="event-access-grid"><div className="qr-frame"><img src={access.qrDataUrl} alt="QR Zoom APTFI"/></div><div className="access-instructions"><strong>Pelatihan Preseptor Online</strong><p>Akses ini bersifat khusus peserta terverifikasi. Jangan meneruskan link atau QR ke pihak lain.</p><a className="btn btn-brand-primary btn-block" href={access.zoomUrl} target="_blank" rel="noreferrer">Buka Zoom Meeting ↗</a><small>Jika Zoom belum dapat dibuka, periksa kembali pengumuman panitia atau coba beberapa saat sebelum acara.</small></div></div></section>
}
