'use client';
import { useEffect,useRef,useState } from 'react';
import { getSupabaseBrowser } from '../lib/supabase-browser';

const statusLabel={incomplete:'Perlu dilengkapi',pending:'Menunggu verifikasi',valid:'Valid',rejected:'Perlu perbaikan',verified:'Terverifikasi'};
function statusClass(v){return ['valid','verified'].includes(v)?'status-ok':v==='rejected'?'status-bad':'status-pending'}
function docLabel(type){return type==='stra'?'STRA':type==='experience'?'Bukti pengalaman':'Bukti pembayaran'}
function fmtDate(v){if(!v)return '';try{return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v))}catch{return v}}

export default function ParticipantDashboard(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[type,setType]=useState('');
  const [tab,setTab]=useState('registration'),[announcements,setAnnouncements]=useState([]),[unreadCount,setUnreadCount]=useState(0),[selectedAnnouncement,setSelectedAnnouncement]=useState(null);
  const [eventAccess,setEventAccess]=useState(null),[accessLoading,setAccessLoading]=useState(false),[billingModal,setBillingModal]=useState(null);
  const billingCache=useRef(new Map());
  async function token(){const {data}=await getSupabaseBrowser().auth.getSession();return data.session?.access_token||''}
  async function loadAnnouncements(){const t=await token();if(!t)return;const r=await fetch('/api/me/announcements',{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(r.ok){setAnnouncements(j.announcements||[]);setUnreadCount(j.unreadCount||0)}}
  async function loadEventAccess(){const t=await token();if(!t)return;setAccessLoading(true);const r=await fetch('/api/me/event-access',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setEventAccess(j);setAccessLoading(false)}
  async function load(){const t=await token();if(!t){location.href='/login';return}const r=await fetch('/api/me/registrations',{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(!r.ok)setError(j.message);else{setData(j.registration);setType(j.registration?.participant_type||'')}await Promise.all([loadAnnouncements(),loadEventAccess()])}
  useEffect(()=>{const requested=new URLSearchParams(location.search).get('tab');if(['announcements','access'].includes(requested))setTab(requested);load();return()=>{for(const item of billingCache.current.values()){if(item?.url)URL.revokeObjectURL(item.url)}}},[]);
  async function complete(e){e.preventDefault();setBusy(true);setError('');setNotice('');const t=await token();const fd=new FormData(e.currentTarget);const r=await fetch('/api/me/requirements',{method:'POST',headers:{Authorization:`Bearer ${t}`},body:fd});const j=await r.json();if(!r.ok)setError(j.message);else{setNotice('Dokumen persyaratan berhasil dikirim ulang dan menunggu verifikasi.');await load()}setBusy(false)}
  async function reuploadPayment(e){e.preventDefault();setBusy(true);setError('');setNotice('');const t=await token();const fd=new FormData(e.currentTarget);const r=await fetch('/api/me/payment',{method:'POST',headers:{Authorization:`Bearer ${t}`},body:fd});const j=await r.json();if(!r.ok)setError(j.message);else{setNotice('Bukti pembayaran berhasil dikirim ulang dan menunggu verifikasi.');await load()}setBusy(false)}
  async function openBilling(kind){try{setError('');const cached=billingCache.current.get(kind);if(cached?.url){setBillingModal({loading:false,kind,url:cached.url});return}setBillingModal({loading:true,kind});const t=await token();const r=await fetch(`/api/billing/${kind}?id=${data.id}`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.message||'Dokumen belum tersedia.')}const blob=await r.blob();const url=URL.createObjectURL(blob);billingCache.current.set(kind,{url});setBillingModal({loading:false,kind,url})}catch(e){setBillingModal(null);setError(e.message)}}
  async function openAnnouncement(a){setSelectedAnnouncement(a);if(!a.is_read){const t=await token();await fetch('/api/me/announcements',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({announcementId:a.id})});setAnnouncements(list=>list.map(x=>x.id===a.id?{...x,is_read:true,read_at:new Date().toISOString()}:x));setUnreadCount(v=>Math.max(0,v-1))}}
  async function logout(){await getSupabaseBrowser().auth.signOut();location.href='/'}
  if(!data&&!error)return <main className="participant-shell"><div className="participant-appbar"><img src="/aptfi-logo.png" alt="APTFI"/></div><div className="participant-loading"><div className="spinner"/><p>Memuat pendaftaran...</p></div></main>;
  if(error&&!data)return <main className="participant-shell"><div className="alert alert-error">{error}</div><a className="btn btn-secondary" href="/login">Kembali ke login</a></main>;

  const practitioner=['practitioner','lecturer_practitioner'].includes(type),lecturer=['lecturer','lecturer_practitioner'].includes(type);
  const completeStatus=data.requirements_status==='valid'&&data.payment_status==='verified';
  const docs=data.documents||{};
  const rejectedRequirements=['stra','experience'].filter(k=>docs[k]?.status==='rejected');
  const paymentRejected=data.payment_status==='rejected';

  return <main className="participant-page"><div className="participant-shell">
    <header className="participant-header"><a href="/" className="participant-brand"><img src="/aptfi-logo.png" alt="APTFI"/></a><button className="btn btn-secondary btn-small" onClick={logout}>Keluar</button></header>
    <div className="participant-welcome"><span>Halo,</span><h1>{data.full_name}</h1></div>
    <nav className="participant-tabs"><button className={tab==='registration'?'active':''} onClick={()=>setTab('registration')}>Pendaftaran</button><button className={tab==='announcements'?'active':''} onClick={()=>setTab('announcements')}>Pengumuman {unreadCount>0&&<em>{unreadCount}</em>}</button><button className={tab==='access'?'active':''} onClick={()=>{setTab('access');loadEventAccess()}}>Akses Acara</button></nav>
    {error&&<div className="alert alert-error">{error}</div>}{notice&&<div className="alert alert-success">{notice}</div>}

    {tab==='announcements'?<AnnouncementPanel announcements={announcements} unreadCount={unreadCount} selectedAnnouncement={selectedAnnouncement} openAnnouncement={openAnnouncement} close={()=>setSelectedAnnouncement(null)}/>:tab==='access'?<EventAccessPanel access={eventAccess} loading={accessLoading} refresh={loadEventAccess}/>:<>
      <section className={`participant-status-hero ${completeStatus?'complete':''}`}><div><div className="eyebrow light">Status Pendaftaran</div><h2>{completeStatus?'Pendaftaran terverifikasi':'Pendaftaran sedang diproses'}</h2><p>{completeStatus?'Persyaratan dan pembayaran Anda sudah terverifikasi oleh panitia.':'Pantau progres verifikasi di halaman ini. Jika ada perbaikan, instruksinya akan ditampilkan di bawah.'}</p></div><div className="registration-code"><span>Nomor pendaftaran</span><strong>{data.registration_code}</strong></div></section>
      <section className="participant-progress"><div className={`progress-card ${statusClass(data.requirements_status)}`}><div className="progress-icon">1</div><div><span>Persyaratan</span><strong>{statusLabel[data.requirements_status]||data.requirements_status}</strong><small>STRA & bukti pengalaman</small></div></div><div className={`progress-card ${statusClass(data.payment_status)}`}><div className="progress-icon">2</div><div><span>Pembayaran</span><strong>{statusLabel[data.payment_status]||data.payment_status}</strong><small>Bukti transfer</small></div></div><div className={`progress-card ${completeStatus?'status-ok':'status-pending'}`}><div className="progress-icon">3</div><div><span>Status akhir</span><strong>{completeStatus?'Terverifikasi':'Dalam proses'}</strong><small>Konfirmasi akhir peserta</small></div></div></section>

      <section className="participant-card billing-card"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Dokumen Keuangan</div><h2>Tagihan & Kwitansi</h2><p>Tagihan tersedia sejak pendaftaran. Kwitansi diterbitkan setelah pembayaran terverifikasi.</p></div></div><div className="billing-actions"><button className="billing-document" onClick={()=>openBilling('invoice')}><span className="billing-icon">↓</span><span><strong>Tagihan / Invoice</strong><small>PDF · Rp 1.000.000</small></span></button><button className={`billing-document ${data.payment_status!=='verified'?'disabled':''}`} disabled={data.payment_status!=='verified'} onClick={()=>openBilling('receipt')}><span className="billing-icon">✓</span><span><strong>Kwitansi</strong><small>{data.payment_status==='verified'?'PDF · pembayaran terverifikasi':'Tersedia setelah verifikasi'}</small></span></button></div></section>

      {completeStatus&&<section className="participant-card access-teaser"><div><div className="eyebrow brand-blue">Akses Pelaksanaan</div><h2>{data.attendance_mode==='Offline'?'QR check-in lokasi':'Akses Zoom'}</h2><p>Akses acara akan tersedia pada waktu yang ditentukan panitia.</p></div><button className="btn btn-brand-primary" onClick={()=>{setTab('access');loadEventAccess()}}>Lihat Akses Acara</button></section>}

      {rejectedRequirements.map(key=><section className="participant-card rejection-card" key={key}><div className="rejection-icon">!</div><div><div className="eyebrow danger-text">Perlu diperbaiki</div><h2>{docLabel(key)} ditolak</h2><p><strong>Catatan panitia:</strong> {docs[key]?.review_note||'Silakan periksa kembali dokumen.'}</p><p><strong>Langkah selanjutnya:</strong> {docs[key]?.next_action||'Unggah dokumen yang benar melalui form di bawah.'}</p></div></section>)}
      {paymentRejected&&<section className="participant-card rejection-card"><div className="rejection-icon">!</div><div><div className="eyebrow danger-text">Perlu diperbaiki</div><h2>Bukti pembayaran ditolak</h2><p><strong>Catatan panitia:</strong> {docs.payment_proof?.review_note||'Silakan periksa kembali bukti pembayaran.'}</p><p><strong>Langkah selanjutnya:</strong> {docs.payment_proof?.next_action||'Unggah ulang bukti pembayaran melalui form di bawah.'}</p></div></section>}

      <section className="participant-card"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Ringkasan</div><h2>Data Pendaftaran</h2></div><span className="mode-chip">{data.attendance_mode||'—'}</span></div><div className="participant-details"><div><span>Email</span><strong>{data.email}</strong></div><div><span>WhatsApp</span><strong>{data.whatsapp||'—'}</strong></div><div><span>Nomor STRA</span><strong>{data.stra_number||'Belum dilengkapi'}</strong></div><div><span>Homebase</span><strong>{data.university||'—'}</strong></div><div><span>Mode keikutsertaan</span><strong>{data.attendance_mode||'—'}</strong></div></div></section>

      {['incomplete','rejected'].includes(data.requirements_status)&&<form onSubmit={complete} className="participant-card requirement-form"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Perlu tindakan</div><h2>{data.requirements_status==='incomplete'?'Lengkapi Persyaratan':'Perbaiki Dokumen Persyaratan'}</h2><p>Pendaftaran Anda tetap tercatat. Dokumen yang tidak bermasalah tidak perlu diunggah ulang.</p></div><span className="status status-bad">{statusLabel[data.requirements_status]}</span></div><div className="field"><label>Nomor STRA</label><input name="stra_number" defaultValue={data.stra_number||''} required placeholder="Masukkan nomor STRA"/></div><div className="field"><label>Kategori peserta</label><select name="participant_type" value={type} onChange={e=>setType(e.target.value)} required><option value="">Pilih kategori</option><option value="practitioner">Praktisi</option><option value="lecturer">Dosen</option><option value="lecturer_practitioner">Dosen sekaligus praktisi</option></select></div>{practitioner&&<div className="grid grid-3"><div className="field"><label>Jenis tempat praktik</label><select name="practice_type" defaultValue={data.practice_type||''} required><option value="">Pilih</option><option>Apotek</option><option>Rumah Sakit (RS)</option><option>Industri</option><option>PBF</option><option>Puskesmas</option></select></div><div className="field"><label>Nama tempat praktik</label><input name="practice_name" defaultValue={data.practice_name||''} required/></div><div className="field"><label>Lama praktik (tahun)</label><input name="practice_years" defaultValue={data.practice_years||''} type="number" min="0" step="0.5" required/></div></div>}{lecturer&&<div className="field"><label>Lama mengajar (tahun)</label><input name="teaching_years" defaultValue={data.teaching_years||''} type="number" min="0" step="0.5" required/></div>}<div className="grid grid-2">{(!docs.stra||docs.stra.status==='rejected')&&<div className="field upload modern-upload"><label>Bukti STRA</label><small>PDF/JPG/PNG · maks. 5 MB</small><input type="file" name="stra_proof" accept="image/jpeg,image/png,application/pdf" required/></div>}{(!docs.experience||docs.experience.status==='rejected')&&<div className="field upload modern-upload"><label>Bukti pengalaman</label><small>Surat keterangan, SK, atau dokumen relevan.</small><input type="file" name="experience_proof" accept="image/jpeg,image/png,application/pdf" required/></div>}</div><button className="btn btn-brand-primary btn-block-mobile" disabled={busy}>{busy?'Menyimpan...':'Kirim Perbaikan Dokumen'}</button></form>}
      {paymentRejected&&<form onSubmit={reuploadPayment} className="participant-card payment-reupload"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Perbaikan Pembayaran</div><h2>Unggah ulang bukti pembayaran</h2><p>Gunakan bukti transfer yang sesuai dengan arahan panitia.</p></div></div><div className="field upload modern-upload"><label>Bukti pembayaran baru</label><small>PDF/JPG/PNG · maks. 5 MB</small><input type="file" name="payment_proof" accept="image/jpeg,image/png,application/pdf" required/></div><button className="btn btn-brand-primary" disabled={busy}>{busy?'Mengunggah...':'Kirim Bukti Pembayaran'}</button></form>}
      {!['incomplete','rejected'].includes(data.requirements_status)&&<section className="participant-card info-card"><div className="info-icon">✓</div><div><h3>Dokumen sudah diterima</h3><p>{data.requirements_status==='valid'?'Dokumen persyaratan telah dinyatakan valid oleh panitia.':'Dokumen Anda sedang diperiksa oleh panitia.'}</p></div></section>}
    </>}
    <footer className="participant-footer"><span>APTFI · Pelatihan Preseptor 2026</span><a href="/">Beranda</a></footer>
    {billingModal&&<ParticipantBillingModal modal={billingModal} registrationCode={data.registration_code} onClose={()=>setBillingModal(null)}/>}
  </div></main>
}


function ParticipantBillingModal({modal,registrationCode,onClose}){
  const title=modal.kind==='receipt'?'Kwitansi Pembayaran':'Tagihan / Invoice';
  if(modal.loading)return <div className="modal-backdrop"><div className="billing-modal loading-modal"><div className="spinner"/><p>Menyiapkan {title.toLowerCase()}...</p><small>Dokumen akan tampil di halaman ini.</small></div></div>;
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="billing-modal participant-billing-modal"><header className="document-modal-header"><div><div className="eyebrow brand-blue">Dokumen Keuangan</div><h2>{title}</h2><p>{registrationCode}</p></div><button className="modal-close" onClick={onClose} aria-label="Tutup">×</button></header><div className="billing-preview"><iframe title={title} src={modal.url}/></div><footer className="billing-modal-actions"><a className="btn btn-secondary" href={modal.url} target="_blank" rel="noreferrer">Buka tab baru ↗</a><a className="btn btn-brand-primary" href={modal.url} download={`${modal.kind==='receipt'?'kwitansi':'tagihan'}-${registrationCode}.pdf`}>Unduh PDF</a></footer></section></div>
}

function AnnouncementPanel({announcements,unreadCount,selectedAnnouncement,openAnnouncement,close}){
  return <section className="participant-card announcement-center"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Informasi Panitia</div><h2>Pengumuman</h2><p>Klik subject untuk membaca isi pengumuman.</p></div>{unreadCount>0&&<span className="status status-info">{unreadCount} baru</span>}</div>{!announcements.length?<div className="empty-state compact"><h3>Belum ada pengumuman</h3><p>Informasi terbaru dari panitia akan tampil di sini.</p></div>:<div className="announcement-list">{announcements.map(a=><button key={a.id} className={`announcement-subject ${a.is_read?'read':'unread'}`} onClick={()=>openAnnouncement(a)}><span className="announcement-dot"/><span><strong>{a.subject}</strong><small>{fmtDate(a.published_at)}</small></span><b>›</b></button>)}</div>}{selectedAnnouncement&&<article className="announcement-detail"><button className="announcement-detail-close" onClick={close}>×</button><div className="eyebrow brand-blue">Pengumuman</div><h2>{selectedAnnouncement.subject}</h2><small>{fmtDate(selectedAnnouncement.published_at)}</small><div className="announcement-rich" dangerouslySetInnerHTML={{__html:selectedAnnouncement.body_html}}/></article>}</section>
}

function EventAccessPanel({access,loading,refresh}){
  if(loading&&!access)return <section className="participant-card event-access-card"><div className="participant-loading compact"><div className="spinner"/><p>Memuat akses acara...</p></div></section>;
  if(!access)return <section className="participant-card event-access-card"><div className="empty-state compact"><h3>Akses belum tersedia</h3><p>Silakan coba kembali beberapa saat lagi.</p><button className="btn btn-secondary" onClick={refresh}>Muat ulang</button></div></section>;
  if(!access.eligible)return <section className="participant-card event-access-card locked"><div className="access-lock">🔒</div><div className="eyebrow brand-blue">Akses Acara</div><h2>Menunggu verifikasi lengkap</h2><p>QR atau akses Zoom hanya tersedia untuk peserta dengan persyaratan <strong>Valid</strong> dan pembayaran <strong>Terverifikasi</strong>.</p></section>;
  const future=access.releaseAt&&!access.released;
  if(!access.available)return <section className="participant-card event-access-card scheduled"><div className="access-lock">◷</div><div className="eyebrow brand-blue">{access.mode==='Offline'?'QR Check-in':'Akses Zoom'}</div><h2>{!access.enabled?'Belum dipublikasikan':'Akses akan segera tersedia'}</h2><p>{future?`Panitia menjadwalkan akses mulai ${fmtDate(access.releaseAt)} WIB.`:'Panitia belum mempublikasikan akses. Informasi akan muncul otomatis di halaman ini ketika sudah tersedia.'}</p><button className="btn btn-secondary" onClick={refresh}>Periksa kembali</button></section>;
  if(access.kind==='offline')return <section className="participant-card event-access-card available"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Akses Peserta Offline</div><h2>QR Check-in Lokasi</h2><p>Tunjukkan QR ini kepada panitia saat tiba di lokasi. QR diverifikasi langsung ke sistem APTFI.</p></div><span className={`status ${access.checkedInAt?'status-ok':'status-info'}`}>{access.checkedInAt?'Sudah check-in':'Siap digunakan'}</span></div><div className="event-access-grid"><div className="qr-frame"><img src={access.qrDataUrl} alt="QR Check-in APTFI"/></div><div className="access-instructions"><strong>Petunjuk</strong><ol><li>Buka halaman ini saat tiba di lokasi.</li><li>Tunjukkan QR kepada panitia.</li><li>Panitia memindai QR dan memvalidasi status secara online.</li></ol>{access.checkedInAt&&<div className="checked-in-box"><span>Check-in tercatat</span><strong>{fmtDate(access.checkedInAt)} WIB</strong></div>}<small>Jangan bagikan QR kepada peserta lain. QR terhubung dengan pendaftaran Anda.</small></div></div></section>;
  return <section className="participant-card event-access-card available"><div className="participant-card-head"><div><div className="eyebrow brand-blue">Akses Peserta Online</div><h2>Join Zoom Meeting</h2><p>Scan QR dari perangkat lain atau gunakan tombol di bawah untuk membuka Zoom.</p></div><span className="status status-ok">Tersedia</span></div><div className="event-access-grid"><div className="qr-frame"><img src={access.qrDataUrl} alt="QR Zoom APTFI"/></div><div className="access-instructions"><strong>Pelatihan Preseptor Online</strong><p>Akses ini bersifat khusus peserta terverifikasi. Jangan meneruskan link atau QR ke pihak lain.</p><a className="btn btn-brand-primary btn-block" href={access.zoomUrl} target="_blank" rel="noreferrer">Buka Zoom Meeting ↗</a><small>Jika Zoom belum dapat dibuka, periksa kembali pengumuman panitia atau coba beberapa saat sebelum acara.</small></div></div></section>
}
