'use client';
import { useEffect,useMemo,useState } from 'react';
import { getSupabaseBrowser } from '../lib/supabase-browser';
const labels={requested:'Diajukan',under_review:'Sedang direview',ready:'Siap diproses',processing:'Sedang diproses',refunded:'Sudah refund',rejected:'Ditolak',cancelled:'Dibatalkan'};
function money(v){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0))}
function dt(v){return v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'—'}
function statusClass(v){return v==='refunded'?'status-ok':['rejected','cancelled'].includes(v)?'status-bad':'status-pending'}
export default function RefundManagement(){
  const [refunds,setRefunds]=useState([]),[batches,setBatches]=useState([]),[filter,setFilter]=useState('active'),[selected,setSelected]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function token(){const {data}=await getSupabaseBrowser().auth.getSession();return data.session?.access_token||''}async function api(url,opts={}){const t=await token();const r=await fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Request gagal.');return j}async function load(){try{const j=await api('/api/admin/refunds');setRefunds(j.refunds||[]);setBatches(j.batches||[]);setSelected(v=>v.filter(id=>(j.refunds||[]).some(x=>x.id===id&&x.status==='ready')))}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
  const shown=useMemo(()=>refunds.filter(x=>filter==='all'?true:filter==='active'?!['refunded','rejected','cancelled'].includes(x.status):x.status===filter),[refunds,filter]);const stats=useMemo(()=>({review:refunds.filter(x=>['requested','under_review'].includes(x.status)).length,ready:refunds.filter(x=>x.status==='ready').length,processing:refunds.filter(x=>x.status==='processing').length,done:refunds.filter(x=>x.status==='refunded').length,readyAmount:refunds.filter(x=>x.status==='ready').reduce((s,x)=>s+Number(x.approved_amount||x.requested_amount||0),0)}),[refunds]);
  async function update(item,action){let note='',amount=item.approved_amount??item.requested_amount;if(action==='reject'){note=prompt('Alasan penolakan refund (wajib):','')||'';if(!note.trim())return}if(action==='ready'){const raw=prompt('Nominal refund yang disetujui:',String(Math.round(Number(amount||0))));if(raw===null)return;amount=Number(raw);note=prompt('Catatan panitia (opsional):','')||''}try{setBusy(true);setError('');await api('/api/admin/refunds',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,action,note,amount})});setNotice(action==='ready'?'Refund masuk antrean siap diproses.':action==='reject'?'Refund ditolak.':'Status diperbarui.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function editRefund(item){const bank=prompt('Nama bank:',item.bank_name||'');if(bank===null)return;const account=prompt('Nomor rekening:',item.account_number||'');if(account===null)return;const holder=prompt('Nama pemilik rekening:',item.account_holder||'');if(holder===null)return;const raw=prompt('Nominal refund:',String(Math.round(Number(item.approved_amount||item.requested_amount||0))));if(raw===null)return;const note=prompt('Catatan panitia (opsional):',item.admin_note||'')||'';try{setBusy(true);setError('');await api('/api/admin/refunds',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,action:'update',bank_name:bank,account_number:account,account_holder:holder,amount:Number(raw),note})});setNotice('Data refund diperbarui.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  function toggle(id){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  async function createBatch(){if(!selected.length)return;const notes=prompt('Catatan batch (opsional):','')||'';if(!confirm(`Buat batch untuk ${selected.length} refund terpilih?`))return;try{setBusy(true);const j=await api('/api/admin/refunds/batch',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected,notes})});setNotice(`Batch ${j.batch.batch_code} dibuat.`);setSelected([]);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function completeBatch(batch){const ref=prompt('Referensi transfer / nomor transaksi batch:',batch.batch_code);if(ref===null)return;if(!confirm(`Tandai batch ${batch.batch_code} sebagai selesai dan kirim email ke peserta?`))return;try{setBusy(true);await api('/api/admin/refunds/batch',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:batch.id,action:'complete',transfer_reference:ref})});setNotice('Batch refund selesai.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function cancelBatch(batch){if(!confirm(`Batalkan batch ${batch.batch_code}? Refund akan kembali ke status Siap Diproses.`))return;try{setBusy(true);await api('/api/admin/refunds/batch',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:batch.id,action:'cancel'})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function exportBatch(batch){const rows=refunds.filter(x=>x.batch_id===batch.id);if(!rows.length){setError('Data refund pada batch belum termuat. Muat ulang dashboard.');return}try{const {default:writeXlsxFile}=await import('write-excel-file');const schema=[{column:'No',type:Number,value:r=>r.no},{column:'Batch',type:String,value:r=>r.batch},{column:'No. Registrasi',type:String,value:r=>r.registration_code},{column:'Nama Peserta',type:String,value:r=>r.name},{column:'Bank',type:String,value:r=>r.bank},{column:'Nomor Rekening',type:String,value:r=>r.account},{column:'Nama Pemilik Rekening',type:String,value:r=>r.holder},{column:'Nominal Refund',type:Number,format:'#,##0',value:r=>r.amount},{column:'Email',type:String,value:r=>r.email},{column:'WhatsApp',type:String,value:r=>r.whatsapp}];const data=rows.map((x,i)=>({no:i+1,batch:batch.batch_code,registration_code:x.registration?.registration_code||'',name:x.registration?.full_name||'',bank:x.bank_name,account:x.account_number,holder:x.account_holder,amount:Number(x.approved_amount||x.requested_amount||0),email:x.registration?.email||'',whatsapp:x.registration?.whatsapp||''}));await writeXlsxFile(data,{schema,fileName:`refund-${batch.batch_code}.xlsx`})}catch(e){setError(`Export gagal: ${e.message}`)}}
  return <div className="refund-admin">{error&&<div className="alert alert-error">{error}</div>}{notice&&<div className="alert alert-success">{notice}</div>}<div className="refund-stats"><article><span>Menunggu review</span><strong>{stats.review}</strong></article><article><span>Siap diproses</span><strong>{stats.ready}</strong><small>{money(stats.readyAmount)}</small></article><article><span>Dalam batch</span><strong>{stats.processing}</strong></article><article><span>Selesai</span><strong>{stats.done}</strong></article></div>
    <section className="panel refund-list-panel"><div className="panel-head"><div><h2>Antrean Refund</h2><p>Review, siapkan, lalu proses transfer secara batch.</p></div><div className="refund-toolbar"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Aktif</option><option value="requested">Diajukan</option><option value="under_review">Sedang direview</option><option value="ready">Siap</option><option value="processing">Processing</option><option value="refunded">Selesai</option><option value="all">Semua</option></select><button className="btn btn-brand-primary btn-small" disabled={!selected.length||busy} onClick={createBatch}>Buat Batch ({selected.length})</button></div></div><div className="refund-table-wrap"><table className="refund-table"><thead><tr><th></th><th>Peserta</th><th>Status</th><th>Rekening</th><th>Nominal</th><th>Pengajuan</th><th>Aksi</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><input type="checkbox" checked={selected.includes(x.id)} disabled={x.status!=='ready'} onChange={()=>toggle(x.id)}/></td><td><strong>{x.registration?.full_name||'—'}</strong><small>{x.registration?.registration_code}<br/>{x.registration?.email}</small></td><td><span className={`status ${statusClass(x.status)}`}>{labels[x.status]||x.status}</span></td><td><strong>{x.bank_name}</strong><small>{x.account_number_masked} · {x.account_holder}</small><details><summary>Lihat nomor</summary><code>{x.account_number}</code></details></td><td><strong>{money(x.approved_amount||x.requested_amount)}</strong></td><td><small>{dt(x.requested_at)}</small></td><td><div className="refund-row-actions">{!['processing','refunded'].includes(x.status)&&<button className="btn btn-secondary btn-small" onClick={()=>editRefund(x)} disabled={busy}>Edit</button>}{x.status==='requested'&&<button className="btn btn-secondary btn-small" onClick={()=>update(x,'under_review')} disabled={busy}>Review</button>}{['requested','under_review'].includes(x.status)&&<><button className="btn btn-brand-primary btn-small" onClick={()=>update(x,'ready')} disabled={busy}>Siapkan</button><button className="btn btn-danger btn-small" onClick={()=>update(x,'reject')} disabled={busy}>Tolak</button></>}</div></td></tr>)}</tbody></table></div></section>
    <section className="panel refund-batch-panel"><div className="panel-head"><div><h2>Batch Refund</h2><p>Export Excel digunakan sebagai daftar transfer massal dan rekonsiliasi.</p></div></div><div className="refund-batches">{batches.length===0?<div className="empty-state compact"><h3>Belum ada batch</h3></div>:batches.map(b=><article key={b.id}><div><strong>{b.batch_code}</strong><small>{b.total_items} peserta · {money(b.total_amount)} · dibuat {dt(b.created_at)}</small></div><span className={`status ${b.status==='completed'?'status-ok':b.status==='cancelled'?'status-bad':'status-pending'}`}>{b.status}</span><button className="btn btn-secondary btn-small" onClick={()=>exportBatch(b)}>Export Excel</button>{b.status==='processing'&&<><button className="btn btn-brand-primary btn-small" onClick={()=>completeBatch(b)} disabled={busy}>Tandai Selesai</button><button className="btn btn-danger btn-small" onClick={()=>cancelBatch(b)} disabled={busy}>Batalkan Batch</button></>}</article>)}</div></section>
  </div>
}
