'use client';
import { useEffect,useMemo,useState } from 'react';
import { getSupabaseBrowser } from '../lib/supabase-browser';
const labels={email_change:'Perubahan email',attendance_mode_change:'Perubahan mode',withdrawal:'Pengunduran diri'};
const statuses={pending:'Menunggu',approved:'Disetujui',rejected:'Ditolak',cancelled:'Dibatalkan'};
function dt(v){return v?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(v)):'—'}
export default function SelfServiceRequestsAdmin({participants=[]}){
  const [rows,setRows]=useState([]),[filter,setFilter]=useState('pending'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[createRefund,setCreateRefund]=useState(false);
  async function token(){const {data}=await getSupabaseBrowser().auth.getSession();return data.session?.access_token||''}async function api(url,opts={}){const t=await token();const r=await fetch(url,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${t}`}});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Request gagal.');return j}async function load(){try{const j=await api('/api/admin/self-service');setRows(j.requests||[])}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
  const shown=useMemo(()=>rows.filter(x=>filter==='all'||x.status===filter),[rows,filter]);
  async function decide(row,decision){const note=decision==='reject'?prompt('Alasan penolakan (wajib):',''):prompt('Catatan panitia (opsional):','');if(decision==='reject'&&!note?.trim())return;try{setBusy(true);setError('');await api('/api/admin/self-service',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:row.id,decision,note:note||''})});setNotice(decision==='approve'?'Pengajuan disetujui.':'Pengajuan ditolak.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function createWithdrawal(e){e.preventDefault();const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));body.type='withdrawal';body.request_refund=createRefund;try{setBusy(true);setError('');await api('/api/admin/self-service',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setNotice('Pengajuan pengunduran diri atas nama peserta berhasil dibuat.');form.reset();setCreateRefund(false);await load()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div className="request-admin-layout">{error&&<div className="alert alert-error">{error}</div>}{notice&&<div className="alert alert-success">{notice}</div>}
    <section className="panel request-admin-list"><div className="panel-head"><div><h2>Permintaan Peserta</h2><p>Review perubahan email, mode kehadiran, dan pengunduran diri.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Menunggu review</option><option value="approved">Disetujui</option><option value="rejected">Ditolak</option><option value="cancelled">Dibatalkan</option><option value="all">Semua</option></select></div>
      {!shown.length?<div className="empty-state compact"><h3>Tidak ada pengajuan</h3><p>Pengajuan peserta akan tampil di sini.</p></div>:<div className="request-admin-rows">{shown.map(r=><article key={r.id} className="request-admin-row"><div className="request-admin-main"><div className="request-admin-title"><strong>{r.registration?.full_name||'Peserta'}</strong><span>{r.registration?.registration_code}</span></div><h3>{labels[r.request_type]||r.request_type}</h3><p>{r.reason||'Tanpa alasan tambahan.'}</p><div className="request-payload">{r.request_type==='email_change'&&<>Email baru: <strong>{r.payload?.new_email}</strong></>}{r.request_type==='attendance_mode_change'&&<>Mode: <strong>{r.registration?.attendance_mode} → {r.payload?.new_mode}</strong></>}{r.request_type==='withdrawal'&&<>Refund: <strong>{r.payload?.request_refund?'Diajukan':'Tidak diajukan'}</strong></>}</div><small>{dt(r.created_at)} · diajukan oleh {r.requested_by_type==='admin'?'admin':'peserta'}</small>{r.admin_note&&<div className="admin-note compact"><strong>Catatan review</strong><p>{r.admin_note}</p></div>}</div><div className="request-admin-actions"><span className={`status ${r.status==='approved'?'status-ok':r.status==='rejected'?'status-bad':'status-pending'}`}>{statuses[r.status]||r.status}</span>{r.status==='pending'&&<><button className="btn btn-brand-primary btn-small" disabled={busy} onClick={()=>decide(r,'approve')}>Setujui</button><button className="btn btn-danger btn-small" disabled={busy} onClick={()=>decide(r,'reject')}>Tolak</button></>}</div></article>)}</div>}
    </section>
    <form className="panel request-admin-create" onSubmit={createWithdrawal}><div className="panel-head"><div><h2>Ajukan atas nama peserta</h2><p>Dipakai jika peserta menghubungi panitia untuk pengunduran diri.</p></div></div><div className="field"><label>Peserta</label><select name="registrationId" required defaultValue=""><option value="" disabled>Pilih peserta</option>{participants.map(p=><option key={p.id} value={p.id}>{p.registration_code} · {p.full_name}</option>)}</select></div><div className="field"><label>Alasan *</label><textarea name="reason" rows="3" required/></div><label className="agreement"><input type="checkbox" checked={createRefund} onChange={e=>setCreateRefund(e.target.checked)}/><span>Sekaligus ajukan refund</span></label>{createRefund&&<div className="refund-bank-grid"><div className="field"><label>Bank</label><input name="bank_name" required/></div><div className="field"><label>No. rekening</label><input name="account_number" required/></div><div className="field"><label>Pemilik rekening</label><input name="account_holder" required/></div></div>}<button className="btn btn-brand-primary" disabled={busy}>Buat Pengajuan</button></form>
  </div>
}
