import { NextResponse } from 'next/server';
import { requireAdmin } from '../../../../lib/auth';
import { getSupabaseAdmin } from '../../../../lib/supabase-admin';
import { eventForSlug,masterOptions } from '../../../../lib/master-data';
import { cleanText } from '../../../../lib/profile';
import { logActivity } from '../../../../lib/audit';
export const dynamic='force-dynamic';

async function ctx(request){const auth=await requireAdmin(request,['super_admin','event_admin']);if(auth.error)return {response:NextResponse.json({message:auth.error},{status:auth.status})};const db=getSupabaseAdmin();const {event,error}=await eventForSlug(db);if(error||!event)return {response:NextResponse.json({message:'Event tidak ditemukan.'},{status:404})};return {auth,db,event}}

export async function GET(request){const c=await ctx(request);if(c.response)return c.response;try{return NextResponse.json({options:await masterOptions(c.db,c.event.id,{activeOnly:false})})}catch(e){console.error(e);return NextResponse.json({message:'Gagal membaca data master.'},{status:500})}}

export async function POST(request){const c=await ctx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));const group=cleanText(b.group_key,80),value=cleanText(b.value,120),label=cleanText(b.label,160);if(group!=='practice_type')return NextResponse.json({message:'Penambahan opsi baru saat ini hanya diizinkan untuk Jenis Tempat Praktik.'},{status:422});if(!value||!label)return NextResponse.json({message:'Value dan label wajib diisi.'},{status:422});const row={event_id:c.event.id,group_key:group,value,label,min_years:b.min_years===''||b.min_years==null?null:Number(b.min_years),sort_order:Number(b.sort_order||100),active:b.active!==false,meta:{}};const {data,error}=await c.db.from('master_data_options').insert(row).select('*').single();if(error){if(error.code==='23505')return NextResponse.json({message:'Opsi dengan value tersebut sudah ada.'},{status:409});console.error(error);return NextResponse.json({message:'Gagal menambah data master.'},{status:500})}await logActivity({actorType:'admin',actorEmail:c.auth.admin?.email||c.auth.user?.email,action:'master_data_created'});return NextResponse.json({ok:true,item:data})}

export async function PATCH(request){const c=await ctx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));if(!b.id)return NextResponse.json({message:'ID data master wajib diisi.'},{status:422});const {data:old}=await c.db.from('master_data_options').select('*').eq('id',b.id).eq('event_id',c.event.id).maybeSingle();if(!old)return NextResponse.json({message:'Data master tidak ditemukan.'},{status:404});const update={updated_at:new Date().toISOString()};if(b.label!=null)update.label=cleanText(b.label,160);if(b.sort_order!=null)update.sort_order=Number(b.sort_order||0);if(Object.prototype.hasOwnProperty.call(b,'active'))update.active=!!b.active;if(old.group_key==='practice_type'&&Object.prototype.hasOwnProperty.call(b,'min_years'))update.min_years=b.min_years===''||b.min_years==null?null:Number(b.min_years);const {data,error}=await c.db.from('master_data_options').update(update).eq('id',old.id).select('*').single();if(error){console.error(error);return NextResponse.json({message:'Gagal memperbarui data master.'},{status:500})}await logActivity({actorType:'admin',actorEmail:c.auth.admin?.email||c.auth.user?.email,action:'master_data_updated'});return NextResponse.json({ok:true,item:data})}

export async function DELETE(request){const c=await ctx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));if(!b.id)return NextResponse.json({message:'ID data master wajib diisi.'},{status:422});const {error}=await c.db.from('master_data_options').update({active:false,updated_at:new Date().toISOString()}).eq('id',b.id).eq('event_id',c.event.id);if(error)return NextResponse.json({message:'Gagal menonaktifkan data master.'},{status:500});await logActivity({actorType:'admin',actorEmail:c.auth.admin?.email||c.auth.user?.email,action:'master_data_deactivated'});return NextResponse.json({ok:true})}
