import { NextResponse } from 'next/server';
import { requireUser } from '../../../../lib/auth';
import { getSupabaseAdmin } from '../../../../lib/supabase-admin';
import { normalizeEmail } from '../../../../lib/normalization';
import { validEmail } from '../../../../lib/validation';
import { cleanText,maskAccount } from '../../../../lib/profile';
import { logActivity } from '../../../../lib/audit';
export const dynamic='force-dynamic';

async function regFor(db,email){return (await db.from('registrations').select('*').ilike('email',email).order('created_at',{ascending:false}).limit(1).maybeSingle()).data}
async function state(db,reg){const [{data:requests},{data:refund}]=await Promise.all([db.from('self_service_requests').select('*').eq('registration_id',reg.id).order('created_at',{ascending:false}),db.from('refund_requests').select('*').eq('registration_id',reg.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);return {requests:requests||[],refund:refund?{...refund,account_number_masked:maskAccount(refund.account_number),account_number:undefined}:null}}

export async function GET(request){const auth=await requireUser(request);if(auth.error)return NextResponse.json({message:auth.error},{status:auth.status});const db=getSupabaseAdmin(),reg=await regFor(db,auth.user.email);if(!reg)return NextResponse.json({message:'Pendaftaran tidak ditemukan.'},{status:404});return NextResponse.json({registration:{id:reg.id,email:reg.email,attendance_mode:reg.attendance_mode,lifecycle_status:reg.lifecycle_status,payment_status:reg.payment_status,amount_due:reg.amount_due},...(await state(db,reg))},{headers:{'Cache-Control':'private, no-store'}})}

export async function POST(request){
  const auth=await requireUser(request);if(auth.error)return NextResponse.json({message:auth.error},{status:auth.status});const db=getSupabaseAdmin(),reg=await regFor(db,auth.user.email);if(!reg)return NextResponse.json({message:'Pendaftaran tidak ditemukan.'},{status:404});const b=await request.json().catch(()=>({}));const action=cleanText(b.action,60);
  if(['withdrawn','rejected'].includes(reg.lifecycle_status)&&!['refund'].includes(action))return NextResponse.json({message:reg.lifecycle_status==='rejected'?'Pendaftaran sudah ditolak. Hanya pengajuan refund yang masih tersedia bila pembayaran terverifikasi.':'Pendaftaran sudah berstatus mengundurkan diri.'},{status:409});
  if(action==='email_change'){
    const newEmail=normalizeEmail(cleanText(b.new_email,190));if(!validEmail(newEmail))return NextResponse.json({message:'Email baru tidak valid.'},{status:422});if(newEmail===normalizeEmail(reg.email))return NextResponse.json({message:'Email baru sama dengan email saat ini.'},{status:422});const {data:dup}=await db.from('registrations').select('id').eq('event_id',reg.event_id).eq('normalized_email',newEmail).neq('id',reg.id).limit(1).maybeSingle();if(dup)return NextResponse.json({message:'Email tersebut sudah digunakan pendaftaran lain.'},{status:409});const {error}=await db.from('self_service_requests').insert({event_id:reg.event_id,registration_id:reg.id,request_type:'email_change',payload:{new_email:newEmail},reason:cleanText(b.reason,1000),requested_by_type:'participant',requested_by_email:auth.user.email});if(error){if(error.code==='23505')return NextResponse.json({message:'Masih ada pengajuan perubahan email yang menunggu review.'},{status:409});return NextResponse.json({message:'Gagal membuat pengajuan.'},{status:500})}
  }else if(action==='attendance_mode_change'){
    const mode=cleanText(b.new_mode,20);if(!['Online','Offline'].includes(mode)||mode===reg.attendance_mode)return NextResponse.json({message:'Pilih mode tujuan yang berbeda.'},{status:422});const reason=cleanText(b.reason,1000);if(reason.length<5)return NextResponse.json({message:'Alasan perubahan mode wajib diisi.'},{status:422});const {error}=await db.from('self_service_requests').insert({event_id:reg.event_id,registration_id:reg.id,request_type:'attendance_mode_change',payload:{new_mode:mode},reason,requested_by_type:'participant',requested_by_email:auth.user.email});if(error){if(error.code==='23505')return NextResponse.json({message:'Masih ada pengajuan perubahan mode yang menunggu review.'},{status:409});return NextResponse.json({message:'Gagal membuat pengajuan.'},{status:500})}
  }else if(action==='withdrawal'){
    const reason=cleanText(b.reason,1500);if(reason.length<5)return NextResponse.json({message:'Alasan pengunduran diri wajib diisi.'},{status:422});const requestRefund=!!b.request_refund;if(requestRefund&&reg.payment_status!=='verified')return NextResponse.json({message:'Refund hanya dapat diajukan untuk pembayaran yang sudah terverifikasi.'},{status:422});let requestRow;const {data,error}=await db.from('self_service_requests').insert({event_id:reg.event_id,registration_id:reg.id,request_type:'withdrawal',payload:{request_refund:requestRefund},reason,requested_by_type:'participant',requested_by_email:auth.user.email}).select('*').single();if(error){if(error.code==='23505')return NextResponse.json({message:'Pengajuan pengunduran diri sebelumnya masih menunggu review.'},{status:409});return NextResponse.json({message:'Gagal membuat pengajuan pengunduran diri.'},{status:500})}requestRow=data;await db.from('registrations').update({lifecycle_status:'withdrawal_requested',updated_at:new Date().toISOString()}).eq('id',reg.id);
    if(requestRefund){const bank=cleanText(b.bank_name,120),number=cleanText(b.account_number,80).replace(/\s+/g,''),holder=cleanText(b.account_holder,160);if(!bank||number.length<5||!holder){await db.from('self_service_requests').delete().eq('id',requestRow.id);await db.from('registrations').update({lifecycle_status:'active'}).eq('id',reg.id);return NextResponse.json({message:'Bank, nomor rekening, dan nama pemilik rekening wajib diisi untuk refund.'},{status:422})}const amount=Number(reg.amount_due||1000000);const {error:rErr}=await db.from('refund_requests').insert({event_id:reg.event_id,registration_id:reg.id,withdrawal_request_id:requestRow.id,status:'requested',requested_amount:amount,bank_name:bank,account_number:number,account_holder:holder,reason});if(rErr){console.error('refund create:',rErr);await db.from('self_service_requests').delete().eq('id',requestRow.id);await db.from('registrations').update({lifecycle_status:'active'}).eq('id',reg.id);return NextResponse.json({message:'Pengajuan refund gagal dibuat. Silakan coba lagi.'},{status:500})}}
  }else if(action==='refund'){
    if(!['withdrawn','rejected'].includes(reg.lifecycle_status))return NextResponse.json({message:'Pengajuan refund tersedia setelah pendaftaran berstatus mengundurkan diri atau ditolak.'},{status:409});if(reg.payment_status!=='verified')return NextResponse.json({message:'Pembayaran belum terverifikasi sehingga refund tidak dapat diajukan.'},{status:422});const bank=cleanText(b.bank_name,120),number=cleanText(b.account_number,80).replace(/\s+/g,''),holder=cleanText(b.account_holder,160),reason=cleanText(b.reason,1500);if(!bank||number.length<5||!holder)return NextResponse.json({message:'Data rekening tujuan wajib diisi lengkap.'},{status:422});const {error}=await db.from('refund_requests').insert({event_id:reg.event_id,registration_id:reg.id,status:'requested',requested_amount:Number(reg.amount_due||1000000),bank_name:bank,account_number:number,account_holder:holder,reason});if(error){if(error.code==='23505')return NextResponse.json({message:'Pengajuan refund aktif sudah tersedia.'},{status:409});return NextResponse.json({message:'Gagal membuat pengajuan refund.'},{status:500})}
  }else return NextResponse.json({message:'Jenis pengajuan tidak dikenali.'},{status:422});
  await logActivity({registrationId:reg.id,actorType:'participant',actorEmail:auth.user.email,action:`self_service_${action}_requested`});return NextResponse.json({ok:true,...(await state(db,reg))});
}

export async function DELETE(request){const auth=await requireUser(request);if(auth.error)return NextResponse.json({message:auth.error},{status:auth.status});const db=getSupabaseAdmin(),reg=await regFor(db,auth.user.email);if(!reg)return NextResponse.json({message:'Pendaftaran tidak ditemukan.'},{status:404});const b=await request.json().catch(()=>({}));const {data:req}=await db.from('self_service_requests').select('*').eq('id',b.id).eq('registration_id',reg.id).eq('status','pending').maybeSingle();if(!req)return NextResponse.json({message:'Pengajuan tidak ditemukan atau sudah diproses.'},{status:404});await db.from('self_service_requests').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',req.id);if(req.request_type==='withdrawal'){await db.from('registrations').update({lifecycle_status:'active',updated_at:new Date().toISOString()}).eq('id',reg.id);await db.from('refund_requests').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('withdrawal_request_id',req.id).in('status',['requested','under_review','ready'])}await logActivity({registrationId:reg.id,actorType:'participant',actorEmail:auth.user.email,action:'self_service_request_cancelled'});return NextResponse.json({ok:true,...(await state(db,reg))})}
