import { NextResponse } from 'next/server';
import { requireAdmin } from '../../../../lib/auth';
import { getSupabaseAdmin } from '../../../../lib/supabase-admin';
import { normalizeEmail } from '../../../../lib/normalization';
import { validEmail } from '../../../../lib/validation';
import { cleanText,maskAccount } from '../../../../lib/profile';
import { sendEmail } from '../../../../lib/email';
import { requestEmailHtml,requestLabels } from '../../../../lib/self-service';
import { logActivity } from '../../../../lib/audit';
import { ACTIVE_REGISTRATION_STATUSES,isActiveRegistration } from '../../../../lib/registration-lifecycle';
export const dynamic='force-dynamic';

async function authCtx(request){const auth=await requireAdmin(request,['super_admin','event_admin']);if(auth.error)return {response:NextResponse.json({message:auth.error},{status:auth.status})};return {auth,db:getSupabaseAdmin()}}
async function joined(db){const {data:requests,error}=await db.from('self_service_requests').select('*').order('created_at',{ascending:false});if(error)throw error;const ids=[...new Set((requests||[]).map(x=>x.registration_id))];let regs=[];if(ids.length){const r=await db.from('registrations').select('id,registration_code,full_name,email,whatsapp,university,attendance_mode,payment_status,requirements_status,lifecycle_status,amount_due').in('id',ids);regs=r.data||[]}const map=new Map(regs.map(r=>[r.id,r]));return (requests||[]).map(x=>({...x,registration:map.get(x.registration_id)||null}))}
async function mail(db,reg,subject,message,note=''){const result=await sendEmail({to:reg.email,subject,html:requestEmailHtml({name:reg.full_name,title:subject,message,note})});await db.from('email_logs').insert({registration_id:reg.id,email_type:'self_service',recipient:reg.email,status:result.ok?'sent':result.skipped?'skipped':'failed',provider_id:result.id||null,error_message:result.error||null});return result}

export async function GET(request){const c=await authCtx(request);if(c.response)return c.response;try{return NextResponse.json({requests:await joined(c.db)})}catch(e){console.error(e);return NextResponse.json({message:'Gagal membaca daftar pengajuan.'},{status:500})}}

export async function POST(request){
  const c=await authCtx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));if(b.type!=='withdrawal')return NextResponse.json({message:'Admin saat ini hanya dapat membuat pengajuan pengunduran diri atas nama peserta.'},{status:422});const {data:reg}=await c.db.from('registrations').select('*').eq('id',b.registrationId).maybeSingle();if(!reg)return NextResponse.json({message:'Peserta tidak ditemukan.'},{status:404});if(['withdrawn','rejected'].includes(reg.lifecycle_status))return NextResponse.json({message:'Pendaftaran peserta sudah tidak aktif.'},{status:409});const reason=cleanText(b.reason,1500);if(reason.length<5)return NextResponse.json({message:'Alasan pengunduran diri wajib diisi.'},{status:422});const requestRefund=!!b.request_refund;if(requestRefund&&reg.payment_status!=='verified')return NextResponse.json({message:'Refund hanya bisa diajukan untuk pembayaran terverifikasi.'},{status:422});const {data:req,error}=await c.db.from('self_service_requests').insert({event_id:reg.event_id,registration_id:reg.id,request_type:'withdrawal',payload:{request_refund:requestRefund},reason,requested_by_type:'admin',requested_by_email:c.auth.user.email}).select('*').single();if(error){if(error.code==='23505')return NextResponse.json({message:'Peserta sudah memiliki pengajuan withdrawal yang menunggu review.'},{status:409});return NextResponse.json({message:'Gagal membuat pengajuan.'},{status:500})}await c.db.from('registrations').update({lifecycle_status:'withdrawal_requested',updated_at:new Date().toISOString()}).eq('id',reg.id);
  if(requestRefund){const bank=cleanText(b.bank_name,120),number=cleanText(b.account_number,80).replace(/\s+/g,''),holder=cleanText(b.account_holder,160);if(!bank||number.length<5||!holder){await c.db.from('self_service_requests').delete().eq('id',req.id);await c.db.from('registrations').update({lifecycle_status:'active'}).eq('id',reg.id);return NextResponse.json({message:'Data rekening refund wajib diisi lengkap.'},{status:422})}const {error:rErr}=await c.db.from('refund_requests').insert({event_id:reg.event_id,registration_id:reg.id,withdrawal_request_id:req.id,status:'requested',requested_amount:Number(reg.amount_due||1000000),bank_name:bank,account_number:number,account_holder:holder,reason});if(rErr){await c.db.from('self_service_requests').delete().eq('id',req.id);await c.db.from('registrations').update({lifecycle_status:'active'}).eq('id',reg.id);return NextResponse.json({message:'Gagal membuat data refund.'},{status:500})}}
  await logActivity({registrationId:reg.id,actorType:'admin',actorEmail:c.auth.user.email,action:'withdrawal_requested_by_admin'});return NextResponse.json({ok:true});
}

export async function PATCH(request){
  const c=await authCtx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));const decision=b.decision;const note=cleanText(b.note,1500);if(!['approve','reject'].includes(decision))return NextResponse.json({message:'Keputusan tidak valid.'},{status:422});if(decision==='reject'&&note.length<3)return NextResponse.json({message:'Catatan penolakan wajib diisi.'},{status:422});const {data:req}=await c.db.from('self_service_requests').select('*').eq('id',b.id).eq('status','pending').maybeSingle();if(!req)return NextResponse.json({message:'Pengajuan tidak ditemukan atau sudah diproses.'},{status:404});const {data:reg}=await c.db.from('registrations').select('*').eq('id',req.registration_id).single();if(!reg)return NextResponse.json({message:'Peserta tidak ditemukan.'},{status:404});
  if(decision==='reject'){
    await c.db.from('self_service_requests').update({status:'rejected',admin_note:note,reviewed_by:c.auth.user.email,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',req.id);
    if(req.request_type==='withdrawal'){await c.db.from('registrations').update({lifecycle_status:'active',updated_at:new Date().toISOString()}).eq('id',reg.id);await c.db.from('refund_requests').update({status:'cancelled',admin_note:note,updated_at:new Date().toISOString()}).eq('withdrawal_request_id',req.id).in('status',['requested','under_review','ready'])}
    await mail(c.db,reg,`${requestLabels[req.request_type]} - ditolak`,`Pengajuan ${requestLabels[req.request_type].toLowerCase()} Anda belum dapat disetujui.`,note);await logActivity({registrationId:reg.id,actorType:'admin',actorEmail:c.auth.user.email,action:`${req.request_type}_rejected`});return NextResponse.json({ok:true});
  }
  if(req.request_type==='email_change'){
    const newEmail=normalizeEmail(req.payload?.new_email||'');if(!validEmail(newEmail))return NextResponse.json({message:'Email tujuan pada pengajuan tidak valid.'},{status:422});const {data:dup}=await c.db.from('registrations').select('id').eq('event_id',reg.event_id).eq('normalized_email',newEmail).neq('id',reg.id).limit(1).maybeSingle();if(dup)return NextResponse.json({message:'Email baru sudah digunakan peserta lain.'},{status:409});const users=await c.db.auth.admin.listUsers({page:1,perPage:1000});const authUser=users.data?.users?.find(u=>String(u.email||'').toLowerCase()===String(reg.email||'').toLowerCase());if(!authUser)return NextResponse.json({message:'Akun Auth peserta tidak ditemukan. Jangan ubah email manual; periksa akun peserta terlebih dahulu.'},{status:409});const changed=await c.db.auth.admin.updateUserById(authUser.id,{email:newEmail,email_confirm:true});if(changed.error)return NextResponse.json({message:`Gagal memperbarui email login: ${changed.error.message}`},{status:500});const {error}=await c.db.from('registrations').update({email:newEmail,normalized_email:newEmail,email_needs_update:false,updated_at:new Date().toISOString()}).eq('id',reg.id);if(error){await c.db.auth.admin.updateUserById(authUser.id,{email:reg.email,email_confirm:true}).catch(()=>{});return NextResponse.json({message:'Gagal menyimpan email baru pada pendaftaran.'},{status:500})}reg.email=newEmail;
  }else if(req.request_type==='attendance_mode_change'){
    const mode=req.payload?.new_mode;if(!['Online','Offline'].includes(mode))return NextResponse.json({message:'Mode tujuan tidak valid.'},{status:422});const [{count:total},{count:modeCount},{data:event}]=await Promise.all([c.db.from('registrations').select('id',{count:'exact',head:true}).eq('event_id',reg.event_id).in('lifecycle_status',ACTIVE_REGISTRATION_STATUSES),c.db.from('registrations').select('id',{count:'exact',head:true}).eq('event_id',reg.event_id).in('lifecycle_status',ACTIVE_REGISTRATION_STATUSES).eq('attendance_mode',mode),c.db.from('events').select('quota_total,quota_online,quota_offline').eq('id',reg.event_id).single()]);const sameActive=isActiveRegistration(reg.lifecycle_status);const effectiveTotal=Number(total||0);const effectiveMode=Number(modeCount||0)+(sameActive&&reg.attendance_mode!==mode?1:0);const quota=mode==='Offline'?Number(event?.quota_offline||0):Number(event?.quota_online||0);if(quota>0&&effectiveMode>quota)return NextResponse.json({message:`Kuota ${mode} sudah penuh.`},{status:409});if(Number(event?.quota_total||0)>0&&effectiveTotal>Number(event.quota_total))return NextResponse.json({message:'Kuota total sudah penuh.'},{status:409});await c.db.from('registrations').update({attendance_mode:mode,updated_at:new Date().toISOString()}).eq('id',reg.id);
  }else if(req.request_type==='withdrawal'){
    const now=new Date().toISOString();await c.db.from('registrations').update({lifecycle_status:'withdrawn',withdrawn_at:now,withdrawn_reason:req.reason||'',withdrawn_by:c.auth.user.email,updated_at:now}).eq('id',reg.id);await c.db.from('refund_requests').update({status:'ready',reviewed_at:now,admin_note:note||null,approved_amount:Number(reg.amount_due||1000000),updated_at:now}).eq('withdrawal_request_id',req.id).in('status',['requested','under_review']);
  }
  await c.db.from('self_service_requests').update({status:'approved',admin_note:note||null,reviewed_by:c.auth.user.email,reviewed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',req.id);await mail(c.db,reg,`${requestLabels[req.request_type]} - disetujui`,`Pengajuan ${requestLabels[req.request_type].toLowerCase()} Anda telah disetujui panitia.`,note);await logActivity({registrationId:reg.id,actorType:'admin',actorEmail:c.auth.user.email,action:`${req.request_type}_approved`});return NextResponse.json({ok:true});
}
