-- APTFI Preseptor v0.4.4
-- Managed homebase catalog + safe capacity checks when admins change attendance mode.

create table if not exists public.universities (
  id uuid primary key default gen_random_uuid(),
  name citext not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists universities_active_name_idx on public.universities(active,name);
alter table public.universities enable row level security;

insert into public.universities(name,active) values
  ('Institut Bio Scientia Internasional Indonesia, Jakarta', true),
  ('Institut Kesehatan dan Teknologi Graha Medika', true),
  ('Institut Kesehatan Deli Husada Deli Tua', true),
  ('Institut Kesehatan Helvetia', true),
  ('Institut Kesehatan Medistra Lubuk Pakam', true),
  ('Institut Kesehatan Mitra Bunda Batam', true),
  ('Institut Kesehatan Rajawali', true),
  ('Institut Sains & Teknologi Nasional (ISTN)', true),
  ('Institut Sains dan Teknologi Al Kamal (ISTA) Jakarta', true),
  ('Institut Tarumanagara', true),
  ('Institut Teknologi Bandung', true),
  ('Institut Teknologi dan Kesehatan Bali (ITEKES BALI)', true),
  ('Institut Teknologi dan Kesehatan Bintang Persada', true),
  ('Institut Teknologi Kesehatan (ITEKES) Cendekia Utama Kudus', true),
  ('Institut Teknologi Kesehatan dan Sains Muhammadiyah Sidrap', true),
  ('Institut Teknologi Sains dan Kesehatan RS dr. Soepraoen', true),
  ('Institut Teknologi Sumatera', true),
  ('Sekolah Tinggi Farmasi Indonesia (STFI), Bandung', true),
  ('Sekolah Tinggi Farmasi Mahaganesha', true),
  ('Sekolah Tinggi Farmasi Muhammadiyah Tangerang', true),
  ('Sekolah Tinggi ilmu Farmasi (STF), Riau', true),
  ('Sekolah Tinggi Ilmu Farmasi (STIFA) Pelita Mas, Palu', true),
  ('Sekolah Tinggi Ilmu Farmasi (STIFI) Bhakti Pertiwi Palembang', true),
  ('Sekolah Tinggi Ilmu Farmasi Nusaputra Semarang', true),
  ('Sekolah Tinggi Ilmu Farmasi STIFARM Padang', true),
  ('Sekolah Tinggi Ilmu Farmasi Yayasan Pharmasi Semarang', true),
  ('Sekolah Tinggi Ilmu Kesehatan Adila', true),
  ('Sekolah Tinggi Ilmu Kesehatan Aisyiyah Palembang', true),
  ('Sekolah Tinggi Ilmu Kesehatan Akbidyo', true),
  ('Sekolah Tinggi Ilmu Kesehatan Ar-Rum', true),
  ('Sekolah Tinggi Ilmu Kesehatan Arjuna', true),
  ('Sekolah Tinggi Ilmu Kesehatan As Syifa Kisaran', true),
  ('Sekolah TInggi Ilmu Kesehatan Assyifa Aceh', true),
  ('Sekolah Tinggi Ilmu Kesehatan Bani Saleh, Bekasi', true),
  ('Sekolah Tinggi Ilmu Kesehatan Bhakti Husada Mulia, Madiun', true),
  ('Sekolah Tinggi Ilmu Kesehatan Bhakti Pertiwi Luwu Raya', true),
  ('Sekolah Tinggi Ilmu Kesehatan Bhamada', true),
  ('Sekolah Tinggi Ilmu Kesehatan Bina Cipta Husada', true),
  ('Sekolah Tinggi Ilmu Kesehatan Bogor Husada', true),
  ('Sekolah Tinggi Ilmu Kesehatan Borneo Cendekia Medika', true),
  ('Sekolah Tinggi Ilmu Kesehatan Buleleng', true),
  ('Sekolah Tinggi Ilmu Kesehatan Dirgahayu Samarinda', true),
  ('Sekolah Tinggi Ilmu Kesehatan Har-Kausyar', true),
  ('Sekolah Tinggi Ilmu Kesehatan Harapan Bangsa', true),
  ('Sekolah Tinggi Ilmu Kesehatan Harapan Ibu, Jambi', true),
  ('Sekolah Tinggi Ilmu Kesehatan Ibnu Sina Ajibarang', true),
  ('Sekolah Tinggi Ilmu Kesehatan Ikifa', true),
  ('Sekolah Tinggi Ilmu Kesehatan Indah Medan', true),
  ('Sekolah Tinggi Ilmu Kesehatan ISFI Banjarmasin', true),
  ('Sekolah Tinggi Ilmu Kesehatan Jabal Ghafur', true),
  ('Sekolah Tinggi Ilmu Kesehatan Karya Putra Bangsa, Blitar', true),
  ('Sekolah Tinggi Ilmu Kesehatan Keluarga Bunda Jambi', true),
  ('Sekolah Tinggi Ilmu Kesehatan Kendal', true),
  ('Sekolah Tinggi Ilmu Kesehatan Kusuma Bangsa', true),
  ('Sekolah Tinggi Ilmu Kesehatan Maluku Husada', true),
  ('Sekolah Tinggi Ilmu Kesehatan Mamba''ul ''Ulum Surakarta', true),
  ('Sekolah Tinggi Ilmu Kesehatan Medika Nurul Islam', true),
  ('Sekolah Tinggi Ilmu Kesehatan Medistra Indonesia', true),
  ('Sekolah Tinggi Ilmu Kesehatan Mitra Keluarga, Bekasi', true),
  ('Sekolah Tinggi Ilmu Kesehatan Muhammadiyah Tegal', true),
  ('Sekolah Tinggi Ilmu Kesehatan Muhammadiyah, Kuningan', true),
  ('Sekolah Tinggi Ilmu Kesehatan Namira Madina', true),
  ('Sekolah Tinggi Ilmu Kesehatan Nasional', true),
  ('Sekolah Tinggi Ilmu Kesehatan Nasional Surakarta', true),
  ('Sekolah Tinggi Ilmu Kesehatan Notokusumo Yogyakarta', true),
  ('Sekolah Tinggi Ilmu Kesehatan Panti Waluya Malang', true),
  ('Sekolah Tinggi Ilmu Kesehatan Papua', true),
  ('Sekolah Tinggi Ilmu Kesehatan Pelita Ibu', true),
  ('Sekolah Tinggi Ilmu Kesehatan Prima Indonesia, Bekasi', true),
  ('Sekolah Tinggi Ilmu Kesehatan Rajekwesi Bojonegoro', true),
  ('Sekolah Tinggi Ilmu Kesehatan Salsabila Serang', true),
  ('Sekolah Tinggi Ilmu Kesehatan Samarinda', true),
  ('Sekolah Tinggi Ilmu Kesehatan Sehat Medan', true),
  ('Sekolah Tinggi Ilmu Kesehatan Senior Medan', true),
  ('Sekolah Tinggi Ilmu Kesehatan Serulingmas, Cilacap', true),
  ('Sekolah Tinggi Ilmu Kesehatan Siti Kodijah, Palembang', true),
  ('Sekolah Tinggi Ilmu Kesehatan Telogorejo', true),
  ('Sekolah Tinggi Ilmu Kesehatan Tujuh Belas', true),
  ('Sekolah Tinggi Ilmu Kesehatan Widya Dharma Husada Tanggerang', true),
  ('Sekolah Tinggi Kesehatan Al-Fatah Bengkulu', true),
  ('Sekolah Tinggi Teknologi Industri dan Farmasi (STTIF) Bogor', true),
  ('Universitas 17 Agustus 1945 (UTA`45) Jakarta', true),
  ('Universitas Abdurrab', true),
  ('Universitas Adiwangsa Jambi', true),
  ('Universitas Advent Indonesia', true),
  ('Universitas Ahmad Dahlan (UAD)', true),
  ('Universitas Airlangga', true),
  ('Universitas Aisyah Pringsewu', true),
  ('Universitas Al Ghifari Bandung (UNAG)', true),
  ('Universitas Al Irsyad Cilacap', true),
  ('Universitas Alma Ata', true),
  ('Universitas Almarisah Madani, Makassar', true),
  ('Universitas An Nasher Cirebon', true),
  ('Universitas An-Nuur, Jawa Tengah', true),
  ('Universitas Andalas', true),
  ('Universitas Anwar Medika, Sidoarjo', true),
  ('Universitas Atma Jaya Jakarta', true),
  ('Universitas Audi Indonesia', true),
  ('Universitas Aufa Royhan, Padangsidempuan', true),
  ('Universitas Baiturrahmah', true),
  ('Universitas Bali Dwipa', true),
  ('Universitas Bali Internasional', true),
  ('Universitas Batam', true),
  ('Universitas Bengkulu', true),
  ('Universitas Bhakti Kencana, Bandung', true),
  ('Universitas Bhakti Tunas Husada', true),
  ('Universitas Bhakti Wiyata Kediri, Kediri', true),
  ('Universitas Binawan, Jakarta', true),
  ('Universitas Borneo Lestari, Banjarbaru', true),
  ('Universitas Brawijaya', true),
  ('Universitas Buana Perjuangan Kerawang', true),
  ('Universitas Bumigora', true),
  ('Universitas Cendrawasih (UNCEN)', true),
  ('Universitas Citra Bangsa, Kupang', true),
  ('Universitas Darussalam Gontor (UNIDA Gontor)', true),
  ('Universitas Dharma Andalas', true),
  ('Universitas Diponegoro, Semarang', true),
  ('Universitas dr. Soebandi, Jember', true),
  ('Universitas Duta Bangsa', true),
  ('Universitas Efarina, Simalungun', true),
  ('Universitas Esa Unggul Jakarta', true),
  ('Universitas Fort De Kock Bukittinggi', true),
  ('Universitas Gadjah Mada', true),
  ('Universitas Garut (UNIGA)', true),
  ('Universitas Global, Jakarta', true),
  ('Universitas Gunadarma', true),
  ('Universitas Hafshawaty Zainul Hasan Probolinggo', true),
  ('Universitas Haji Sumatera Utara', true),
  ('Universitas Halim Sanusi', true),
  ('Universitas Halu Oleo, Kendari', true),
  ('Universitas Hamzanwadi, Lombok Timur', true),
  ('Universitas Hang Tuah', true),
  ('Universitas Harapan Bangsa, Purwokerto', true),
  ('Universitas Hasanuddin', true),
  ('Universitas Ibnu Chaldun', true),
  ('Universitas Ibrahimy', true),
  ('Universitas Imelda Medan', true),
  ('Universitas Indonesia', true),
  ('Universitas Indonesia Maju', true),
  ('Universitas Indonesia Timur UIT', true),
  ('Universitas Islam Bandung (UNISBA)', true),
  ('Universitas Islam Indonesia (UII)', true),
  ('Universitas Islam Kalimantan Muhammad Arsyad Al Banjari', true),
  ('Universitas Islam Makassar', true),
  ('Universitas Islam Malang (Unisma)', true),
  ('Universitas Islam Negeri Alauddin, Makassar', true),
  ('Universitas Islam Negeri Maulana Malik Ibrahim Malang', true),
  ('Universitas Islam Negeri UIN Syarif Hidayatullah', true),
  ('Universitas Islam Sultan Agung Semarang', true),
  ('Universitas Jambi', true),
  ('Universitas Jayapura', true),
  ('Universitas Jember (UNEJ)', true),
  ('Universitas Jend. Achmad Yani (Unjani), Cimahi', true),
  ('Universitas Jend. Achmad Yani, Yogyakarta', true),
  ('Universitas Jendral Soedirman (UNSOED)', true),
  ('Universitas Kader Bangsa Palembang', true),
  ('Universitas Kadiri', true),
  ('Universitas Katolik Widya Mandala (UKWM)', true),
  ('Universitas Khairun', true),
  ('Universitas Kristen Immanuel, Sleman', true),
  ('Universitas Kristen Indonesia Tomohon (UKIT)', true),
  ('Universitas Kusuma Husada Surakarta', true),
  ('Universitas Lambung Mangkurat', true),
  ('Universitas Lampung', true),
  ('Universitas Ma Chung', true),
  ('Universitas Mahasaraswati Denpasar', true),
  ('Universitas Malahayati', true),
  ('Universitas Mandala Waluya Kendari', true),
  ('Universitas Mataram', true),
  ('Universitas Mathla''ul Anwar Banten', true),
  ('Universitas Medika Suherman, Bekasi', true),
  ('Universitas Megarezky', true),
  ('Universitas Mohammad Natsir Bukittinggi', true),
  ('Universitas Muhammadiyah Ahmad Dahlan, Cirebon', true),
  ('Universitas Muhammadiyah Bandung', true),
  ('Universitas Muhammadiyah Banjarmasin', true),
  ('Universitas Muhammadiyah Cirebon', true),
  ('Universitas Muhammadiyah Gombong', true),
  ('Universitas Muhammadiyah Kalimantan Timur', true),
  ('Universitas Muhammadiyah Kudus', true),
  ('Universitas Muhammadiyah Lamongan', true),
  ('Universitas Muhammadiyah Magelang', true),
  ('Universitas Muhammadiyah Makassar', true),
  ('Universitas Muhammadiyah Malang', true),
  ('Universitas Muhammadiyah Manado', true),
  ('Universitas Muhammadiyah Mataram', true),
  ('Universitas Muhammadiyah Palopo', true),
  ('Universitas Muhammadiyah Pekajangan, Pekalongan', true),
  ('Universitas Muhammadiyah Prof.Dr.Hamka', true),
  ('Universitas Muhammadiyah Purwokerto (UMP)', true),
  ('Universitas Muhammadiyah Riau', true),
  ('Universitas Muhammadiyah Sumatera Barat', true),
  ('Universitas Muhammadiyah Surabaya', true),
  ('Universitas Muhammadiyah Surakarta (UMS)', true),
  ('Universitas Muhammadiyah Yogyakarta (UMY)', true),
  ('Universitas Mulawarman', true),
  ('Universitas Mulia', true),
  ('Universitas Muslim Indonesia (UMI)', true),
  ('Universitas Muslim Nusantara Washliyah Medan', true),
  ('Universitas Nahdlatul Ulama Kalimantan Selatan', true),
  ('Universitas Nahdlatul Ulama Kalimantan Timur', true),
  ('Universitas Nahdlatul Ulama Sunan Giri, Bojonegoro', true),
  ('Universitas Nahdlatul Ulama, Yogyakarta', true),
  ('Universitas Negeri Gorontalo (UNG)', true),
  ('Universitas Negeri Semarang', true),
  ('Universitas Ngudi Waluyo, Semarang', true),
  ('Universitas Noor Huda Mustofa', true),
  ('Universitas NU Mataram', true),
  ('Universitas Nusa Cendana', true),
  ('Universitas Padjadjaran', true),
  ('Universitas Pakuan (UNPAK), Bogor', true),
  ('Universitas Palangka Raya', true),
  ('Universitas Pancasakti Makasar', true),
  ('Universitas Pancasila (FFUP)', true),
  ('Universitas Pekalongan', true),
  ('Universitas Pelita Harapan', true),
  ('Universitas Pembangunan Nasional Veteran Jakarta', true),
  ('Universitas Pendidikan Muhammadiyah Sorong', true),
  ('Universitas Peradaban', true),
  ('Universitas Perintis Indonesia', true),
  ('Universitas Perjuangan, Tasikmalaya', true),
  ('Universitas Pertahanan', true),
  ('Universitas PGRI Adi Buana Surabaya', true),
  ('Universitas PGRI Madiun', true),
  ('Universitas PGRI Yogyakarta', true),
  ('Universitas Prima Indonesia', true),
  ('Universitas Qamarul Huda', true),
  ('Universitas Sahid Surakarta', true),
  ('Universitas Sains Cut Nyak Dhien', true),
  ('Universitas Sam Ratulangi (UNSRAT)', true),
  ('Universitas Sanatha Dharma (USD)', true),
  ('Universitas Sari Mulia', true),
  ('Universitas Sari Mutiara Indonesia', true),
  ('Universitas Sebelas Maret, Surakarta', true),
  ('Universitas Sembilan belas November Kolaka', true),
  ('Universitas Setia Budi (USB)', true),
  ('Universitas Singaperbangsa Karawang', true),
  ('Universitas Sriwijaya, Palembang', true),
  ('Universitas Strada Indonesia', true),
  ('Universitas Sumatera Barat', true),
  ('Universitas Sumatera Utara', true),
  ('Universitas Surabaya (UBAYA)', true),
  ('Universitas Syah Kuala (UNSYIAH)', true),
  ('Universitas Tadulako, Palu', true),
  ('Universitas Tanjungpura', true),
  ('Universitas Tjut Nyak Dhien, Medan', true),
  ('Universitas Trinita', true),
  ('Universitas Tulang Bawang (UTB), Tanjung Karang', true),
  ('Universitas Ubudiyah Indonesia', true),
  ('Universitas Udayana Bali', true),
  ('Universitas Wahid Hasyim (UNWAHAS), Semarang', true),
  ('Universitas YPIB Majalengka', true)
on conflict (name) do update set active=true, updated_at=now();

create or replace function public.enforce_preseptor_capacity_update() returns trigger
language plpgsql security definer set search_path=public as $$
declare
  ev public.events%rowtype;
  mode_count integer;
begin
  if new.attendance_mode is not distinct from old.attendance_mode then
    return new;
  end if;

  select * into ev from public.events where id=new.event_id for update;
  if not found then
    return new;
  end if;

  if new.attendance_mode='Online' then
    select count(*) into mode_count from public.registrations where event_id=new.event_id and attendance_mode='Online' and id<>new.id;
    if ev.quota_online > 0 and mode_count >= ev.quota_online then
      raise exception using errcode='P0001', message='quota_online_full';
    end if;
  elsif new.attendance_mode='Offline' then
    select count(*) into mode_count from public.registrations where event_id=new.event_id and attendance_mode='Offline' and id<>new.id;
    if ev.quota_offline > 0 and mode_count >= ev.quota_offline then
      raise exception using errcode='P0001', message='quota_offline_full';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists registrations_capacity_update_guard on public.registrations;
create trigger registrations_capacity_update_guard
before update of attendance_mode on public.registrations
for each row execute function public.enforce_preseptor_capacity_update();
