import { NextResponse } from 'next/server';
import { requireAdmin } from '../../../../../lib/auth';
import { getSupabaseAdmin } from '../../../../../lib/supabase-admin';
import { cleanText } from '../../../../../lib/profile';
import { sendEmail } from '../../../../../lib/email';
import { requestEmailHtml } from '../../../../../lib/self-service';
import { logActivity } from '../../../../../lib/audit';
export const dynamic='force-dynamic';

async function ctx(request){const auth=await requireAdmin(request,['super_admin','event_admin','payment_verifier']);if(auth.error)return {response:NextResponse.json({message:auth.error},{status:auth.status})};return {auth,db:getSupabaseAdmin()}}
function jakartaDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()).replaceAll('-','')}
function batchCode(){return `RF-${jakartaDate()}-${String(Math.floor(Math.random()*10000)).padStart(4,'0')}`}

export async function POST(request){
  const c=await ctx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));const ids=Array.isArray(b.ids)?[...new Set(b.ids.filter(Boolean))]:[];if(!ids.length)return NextResponse.json({message:'Pilih minimal satu refund yang siap diproses.'},{status:422});const {data:items}=await c.db.from('refund_requests').select('*').in('id',ids);if(!items?.length||items.some(x=>x.status!=='ready'))return NextResponse.json({message:'Semua refund yang dipilih harus berstatus Siap Diproses.'},{status:409});const eventIds=[...new Set(items.map(x=>x.event_id))];if(eventIds.length!==1)return NextResponse.json({message:'Satu batch hanya boleh berisi satu event.'},{status:422});const total=items.reduce((s,x)=>s+Number(x.approved_amount??x.requested_amount??0),0);let batch=null,error=null;for(let i=0;i<5;i++){const r=await c.db.from('refund_batches').insert({event_id:eventIds[0],batch_code:batchCode(),status:'processing',total_items:items.length,total_amount:total,notes:cleanText(b.notes,1500),created_by:c.auth.user.email}).select('*').single();batch=r.data;error=r.error;if(!error)break}if(error||!batch)return NextResponse.json({message:'Gagal membuat nomor batch refund.'},{status:500});const {error:updateError}=await c.db.from('refund_requests').update({status:'processing',batch_id:batch.id,updated_at:new Date().toISOString()}).in('id',ids).eq('status','ready');if(updateError){await c.db.from('refund_batches').delete().eq('id',batch.id);return NextResponse.json({message:'Gagal memasukkan refund ke batch.'},{status:500})}for(const item of items)await logActivity({registrationId:item.registration_id,actorType:'admin',actorEmail:c.auth.user.email,action:'refund_batch_created'});return NextResponse.json({ok:true,batch});
}

export async function PATCH(request){
  const c=await ctx(request);if(c.response)return c.response;const b=await request.json().catch(()=>({}));const {data:batch}=await c.db.from('refund_batches').select('*').eq('id',b.id).maybeSingle();if(!batch)return NextResponse.json({message:'Batch refund tidak ditemukan.'},{status:404});const action=cleanText(b.action,30);
  if(action==='complete'){
    if(batch.status!=='processing')return NextResponse.json({message:'Hanya batch Processing yang dapat diselesaikan.'},{status:409});const reference=cleanText(b.transfer_reference,250),notes=cleanText(b.notes,1500),now=new Date().toISOString();const {data:items}=await c.db.from('refund_requests').select('*').eq('batch_id',batch.id).eq('status','processing');await c.db.from('refund_requests').update({status:'refunded',processed_at:now,transfer_reference:reference||batch.batch_code,updated_at:now}).eq('batch_id',batch.id).eq('status','processing');await c.db.from('refund_batches').update({status:'completed',completed_at:now,processed_by:c.auth.user.email,notes:notes||batch.notes}).eq('id',batch.id);const ids=(items||[]).map(x=>x.registration_id);let regs=[];if(ids.length){const r=await c.db.from('registrations').select('id,full_name,email').in('id',ids);regs=r.data||[]}const map=new Map(regs.map(r=>[r.id,r]));for(const item of items||[]){const reg=map.get(item.registration_id);if(reg){const result=await sendEmail({to:reg.email,subject:'Refund telah diproses',html:requestEmailHtml({name:reg.full_name,title:'Refund telah diproses',message:`Refund Anda telah ditandai selesai oleh panitia. Referensi: ${reference||batch.batch_code}.`})});await c.db.from('email_logs').insert({registration_id:reg.id,email_type:'refund_completed',recipient:reg.email,status:result.ok?'sent':result.skipped?'skipped':'failed',provider_id:result.id||null,error_message:result.error||null});await logActivity({registrationId:reg.id,actorType:'admin',actorEmail:c.auth.user.email,action:'refund_completed'})}}
  }else if(action==='cancel'){
    if(batch.status!=='processing')return NextResponse.json({message:'Batch tidak dapat dibatalkan.'},{status:409});await c.db.from('refund_requests').update({status:'ready',batch_id:null,updated_at:new Date().toISOString()}).eq('batch_id',batch.id).eq('status','processing');await c.db.from('refund_batches').update({status:'cancelled',processed_by:c.auth.user.email,notes:cleanText(b.notes,1500)||batch.notes}).eq('id',batch.id);
  }else return NextResponse.json({message:'Aksi batch tidak dikenali.'},{status:422});return NextResponse.json({ok:true});
}
