import { NextResponse } from 'next/server';
import { requireAdmin } from '../../../../lib/auth';
import { getSupabaseAdmin } from '../../../../lib/supabase-admin';
import { participantEligible,jakartaDateKey,isTestRegistration } from '../../../../lib/day-h';
export const dynamic='force-dynamic';
function parseWib(v){const s=String(v||'').trim();if(!s)return null;const d=new Date(/([zZ]|[+-]\d{2}:?\d{2})$/.test(s)?s:`${s.length===16?s+':00':s}+07:00`);return Number.isNaN(d.getTime())?null:d}
async function ctx(db){const {data:event}=await db.from('events').select('id,slug,title,day_h_enabled').eq('slug',process.env.NEXT_PUBLIC_EVENT_SLUG||'preseptor-2026').single();if(!event)return {error:'Event tidak ditemukan.'};const {data:days,error}=await db.from('event_days').select('*').eq('event_id',event.id).order('day_number');if(error)return {error:'Migration Day-H belum dijalankan.'};return {event,days:days||[]}}
export async function GET(request){const auth=await requireAdmin(request,['super_admin']);if(auth.error)return NextResponse.json({message:auth.error},{status:auth.status});const db=getSupabaseAdmin(),c=await ctx(db);if(c.error)return NextResponse.json({message:c.error},{status:500});const u=new URL(request.url),requested=u.searchParams.get('dayId'),today=jakartaDateKey();const day=c.days.find(x=>x.id===requested)||c.days.find(x=>x.event_date===today)||c.days[0]||null;const {data:regs}=await db.from('registrations').select('id,registration_code,full_name,email,whatsapp,university,attendance_mode,requirements_status,payment_status,lifecycle_status,is_test_account').eq('event_id',c.event.id).order('full_name');let rec=[];if(day){const q=await db.from('attendance_records').select('*').eq('event_day_id',day.id).order('occurred_at',{ascending:false});rec=q.data||[]}const map=new Map(rec.map(x=>[x.registration_id,x]));const eligible=(regs||[]).filter(participantEligible).map(r=>({...r,checkin:map.get(r.id)||null,test:isTestRegistration(r)}));const official=eligible.filter(x=>!x.test),tests=eligible.filter(x=>x.test);const present=official.filter(x=>x.checkin);return NextResponse.json({event:c.event,days:c.days,selectedDay:day,participants:eligible,stats:{eligible:official.length,present:present.length,absent:Math.max(0,official.length-present.length),offlineEligible:official.filter(x=>x.attendance_mode==='Offline').length,onlineEligible:official.filter(x=>x.attendance_mode==='Online').length,offlinePresent:present.filter(x=>x.attendance_mode==='Offline').length,onlinePresent:present.filter(x=>x.attendance_mode==='Online').length,manual:rec.filter(x=>x.channel==='manual'&&!tests.some(t=>t.id===x.registration_id)).length,testAccounts:tests.length,testPresent:tests.filter(x=>x.checkin).length},recent:rec.slice(0,15).map(a=>({ ...a,participant:eligible.find(x=>x.id===a.registration_id)||null}))},{headers:{'Cache-Control':'private, no-store'}})}
export async function PATCH(request){const auth=await requireAdmin(request,['super_admin']);if(auth.error)return NextResponse.json({message:auth.error},{status:auth.status});const db=getSupabaseAdmin(),c=await ctx(db);if(c.error)return NextResponse.json({message:c.error},{status:500});const b=await request.json().catch(()=>({}));if(Object.prototype.hasOwnProperty.call(b,'day_h_enabled')){const {error}=await db.from('events').update({day_h_enabled:!!b.day_h_enabled}).eq('id',c.event.id);if(error)return NextResponse.json({message:'Gagal mengubah status Hari-H.'},{status:500})}if(b.dayId){const day=c.days.find(x=>x.id===b.dayId);if(!day)return NextResponse.json({message:'Hari tidak ditemukan.'},{status:404});const o=parseWib(b.checkin_open_at),cl=parseWib(b.checkin_close_at);if(b.checkin_open_at&&!o||b.checkin_close_at&&!cl)return NextResponse.json({message:'Format waktu tidak valid.'},{status:422});if(o&&cl&&o>cl)return NextResponse.json({message:'Waktu tutup harus setelah waktu buka.'},{status:422});const {error}=await db.from('event_days').update({active:b.active!==false,checkin_open_at:o?o.toISOString():null,checkin_close_at:cl?cl.toISOString():null,updated_at:new Date().toISOString()}).eq('id',day.id);if(error)return NextResponse.json({message:'Gagal menyimpan jadwal presensi.'},{status:500})}return NextResponse.json({ok:true})}
