import { NextResponse } from 'next/server';
import { requireAdmin } from '../../../../../lib/auth';
import { getSupabaseAdmin } from '../../../../../lib/supabase-admin';
import { normalizeEmail,normalizePhone,normalizeStra } from '../../../../../lib/normalization';
import { validEmail,validStraNumber } from '../../../../../lib/validation';
import { masterOptions,validateProfessionalWithMaster } from '../../../../../lib/master-data';
import { cleanText,displayName } from '../../../../../lib/profile';
import { overallStatus } from '../../../../../lib/status';
import { logActivity } from '../../../../../lib/audit';
export const dynamic='force-dynamic';

async function ctx(request){const auth=await requireAdmin(request,['super_admin','event_admin']);if(auth.error)return {response:NextResponse.json({message:auth.error},{status:auth.status})};return {auth,db:getSupabaseAdmin()}}

export async function GET(request,{params}){const c=await ctx(request);if(c.response)return c.response;const {id}=await params;const {data,error}=await c.db.from('registrations').select('*').eq('id',id).maybeSingle();if(error||!data)return NextResponse.json({message:'Peserta tidak ditemukan.'},{status:404});return NextResponse.json({registration:data})}

export async function PATCH(request,{params}){
  const c=await ctx(request);if(c.response)return c.response;const {id}=await params;const {data:reg}=await c.db.from('registrations').select('*').eq('id',id).maybeSingle();if(!reg)return NextResponse.json({message:'Peserta tidak ditemukan.'},{status:404});const b=await request.json().catch(()=>({}));
  const participantType=cleanText(b.participant_type,40)||null,practiceType=cleanText(b.practice_type,120)||null,practiceName=cleanText(b.practice_name,255)||null,stra=cleanText(b.stra_number,100)||null;
  const nameCore=cleanText(b.name_core||b.full_name||reg.name_core||reg.full_name,255),titlePrefix=cleanText(b.title_prefix??reg.title_prefix,80),titleSuffix=cleanText(b.title_suffix??reg.title_suffix,120),email=normalizeEmail(cleanText(b.email||reg.email,190)),whatsapp=cleanText(b.whatsapp||reg.whatsapp,50),university=cleanText(b.university||reg.university,255),mode=cleanText(b.attendance_mode||reg.attendance_mode,20);
  const data={name_core:nameCore,title_prefix:titlePrefix,title_suffix:titleSuffix,full_name:displayName({name_core:nameCore,title_prefix:titlePrefix,title_suffix:titleSuffix,full_name:reg.full_name}),email,whatsapp,university,attendance_mode:mode,participant_type:participantType,practice_type:practiceType,practice_name:practiceName,practice_years:Number(b.practice_years||0),teaching_years:Number(b.teaching_years||0),stra_number:stra};
  const errors={};if(nameCore.length<3)errors.name_core='Nama wajib diisi.';if(!validEmail(email))errors.email='Email tidak valid.';const normWa=normalizePhone(whatsapp);if(normWa.length<10)errors.whatsapp='Nomor WhatsApp tidak valid.';if(!['Online','Offline'].includes(mode))errors.attendance_mode='Mode keikutsertaan tidak valid.';if(stra&&!validStraNumber(stra))errors.stra_number='Nomor STRA tidak valid.';
  if(participantType){let options={};try{options=await masterOptions(c.db,reg.event_id,{activeOnly:false})}catch{}Object.assign(errors,validateProfessionalWithMaster(data,options,{allowCurrentPracticeType:reg.practice_type||'',allowCurrentParticipantType:reg.participant_type||''}))}
  const [{data:dupEmail},{data:dupWa},{data:dupStra}]=await Promise.all([c.db.from('registrations').select('id').eq('event_id',reg.event_id).eq('normalized_email',email).neq('id',reg.id).limit(1).maybeSingle(),c.db.from('registrations').select('id').eq('event_id',reg.event_id).eq('normalized_whatsapp',normWa).neq('id',reg.id).limit(1).maybeSingle(),stra?c.db.from('registrations').select('id').eq('event_id',reg.event_id).eq('normalized_stra',normalizeStra(stra)).neq('id',reg.id).limit(1).maybeSingle():Promise.resolve({data:null})]);if(dupEmail)errors.email='Email sudah digunakan peserta lain.';if(dupWa)errors.whatsapp='WhatsApp sudah digunakan peserta lain.';if(dupStra)errors.stra_number='STRA sudah digunakan peserta lain.';if(Object.keys(errors).length)return NextResponse.json({message:Object.values(errors)[0],errors},{status:422});
  const {data:uni}=await c.db.from('universities').select('name,active').ilike('name',university).limit(1).maybeSingle();if(!uni&&university!==reg.university)return NextResponse.json({message:'Homebase harus dipilih dari Data Homebase.'},{status:422});
  if(mode!==reg.attendance_mode&&reg.lifecycle_status!=='withdrawn'){const {data:event}=await c.db.from('events').select('quota_online,quota_offline').eq('id',reg.event_id).single();const {count}=await c.db.from('registrations').select('id',{count:'exact',head:true}).eq('event_id',reg.event_id).neq('lifecycle_status','withdrawn').eq('attendance_mode',mode);const quota=mode==='Offline'?Number(event?.quota_offline||0):Number(event?.quota_online||0);if(quota>0&&Number(count||0)>=quota)return NextResponse.json({message:`Kuota ${mode} sudah penuh.`},{status:409})}
  const straChanged=normalizeStra(stra||'')!==normalizeStra(reg.stra_number||''),experienceChanged=['participant_type','practice_type','practice_name'].some(k=>String(data[k]||'')!==String(reg[k]||''))||Number(data.practice_years)!==Number(reg.practice_years||0)||Number(data.teaching_years)!==Number(reg.teaching_years||0),emailChanged=email!==normalizeEmail(reg.email);
  let authUser=null;if(emailChanged){const users=await c.db.auth.admin.listUsers({page:1,perPage:1000});authUser=users.data?.users?.find(u=>String(u.email||'').toLowerCase()===String(reg.email||'').toLowerCase());if(!authUser)return NextResponse.json({message:'Akun login peserta tidak ditemukan sehingga email tidak diubah.'},{status:409});const a=await c.db.auth.admin.updateUserById(authUser.id,{email,email_confirm:true});if(a.error)return NextResponse.json({message:`Gagal memperbarui email login: ${a.error.message}`},{status:500})}
  const update={...data,participant_type:participantType,practice_type:practiceType,practice_name:practiceName,stra_number:stra,normalized_email:email,normalized_whatsapp:normWa,normalized_stra:stra?normalizeStra(stra):null,email_needs_update:false,updated_at:new Date().toISOString()};const reset=[];if(straChanged||experienceChanged){update.requirements_status='pending';update.overall_status=overallStatus('pending',reg.payment_status)}const {error}=await c.db.from('registrations').update(update).eq('id',reg.id);if(error){console.error('admin participant update:',error);if(emailChanged&&authUser)await c.db.auth.admin.updateUserById(authUser.id,{email:reg.email,email_confirm:true}).catch(()=>{});return NextResponse.json({message:process.env.NODE_ENV==='development'?`Database: ${error.message} (${error.code||'no-code'})`:'Gagal memperbarui data peserta.'},{status:500})}
  if(straChanged){const {data:docs}=await c.db.from('registration_documents').select('id').eq('registration_id',reg.id).eq('document_type','stra').order('created_at',{ascending:false}).limit(1);if(docs?.[0]){await c.db.from('registration_documents').update({status:'pending',review_note:null,next_action:null,reviewed_at:null,reviewed_by:null}).eq('id',docs[0].id);reset.push('stra')}}if(experienceChanged){const {data:docs}=await c.db.from('registration_documents').select('id').eq('registration_id',reg.id).eq('document_type','experience').order('created_at',{ascending:false}).limit(1);if(docs?.[0]){await c.db.from('registration_documents').update({status:'pending',review_note:null,next_action:null,reviewed_at:null,reviewed_by:null}).eq('id',docs[0].id);reset.push('experience')}}await logActivity({registrationId:reg.id,actorType:'admin',actorEmail:c.auth.user.email,action:'participant_updated'});return NextResponse.json({ok:true,reviewReset:reset,noChanges:false});
}
